SET IDENTITY_INSERT [dbo].[AddressTypes] ON
INSERT INTO [dbo].[AddressTypes] ([Id], [Name]) VALUES (1, N'HOME')
INSERT INTO [dbo].[AddressTypes] ([Id], [Name]) VALUES (2, N'GP')
SET IDENTITY_INSERT [dbo].[AddressTypes] OFF

SET IDENTITY_INSERT [dbo].[AppUsers] ON
INSERT INTO [dbo].[AppUsers] ([Id], [UserCode], [Active], [SuperUser], [SystemUser]) VALUES (1, N'andrew.jerrison@manchester.ac.uk', 1, 1, 0)
INSERT INTO [dbo].[AppUsers] ([Id], [UserCode], [Active], [SuperUser], [SystemUser]) VALUES (2, N'CRA_Automatic', 1, 0, 1)
INSERT INTO [dbo].[AppUsers] ([Id], [UserCode], [Active], [SuperUser], [SystemUser]) VALUES (3, N'Volpara_Automatic', 1, 0, 1)
SET IDENTITY_INSERT [dbo].[AppUsers] OFF

INSERT INTO [dbo].[AspNetRoles] ([Id], [Name]) VALUES (N'60c25c47-f649-4450-b043-e43312058857', N'General')
INSERT INTO [dbo].[AspNetRoles] ([Id], [Name]) VALUES (N'd8474941-7139-4315-979e-30e42605635e', N'Super')

SET IDENTITY_INSERT [dbo].[EventTypes] ON
INSERT INTO [dbo].[EventTypes] ([Id], [Name], [Code]) VALUES (1, N'Participant Created', N'001')
INSERT INTO [dbo].[EventTypes] ([Id], [Name], [Code]) VALUES (2, N'Consent Received', N'002')
INSERT INTO [dbo].[EventTypes] ([Id], [Name], [Code]) VALUES (3, N'Full Details Added', N'003')
INSERT INTO [dbo].[EventTypes] ([Id], [Name], [Code]) VALUES (4, N'Field Updated', N'004')
INSERT INTO [dbo].[EventTypes] ([Id], [Name], [Code]) VALUES (5, N'Deleted', N'005')
INSERT INTO [dbo].[EventTypes] ([Id], [Name], [Code]) VALUES (6, N'Risk Letter Asked For', N'006')
INSERT INTO [dbo].[EventTypes] ([Id], [Name], [Code]) VALUES (7, N'Risk Letter Received', N'007')
INSERT INTO [dbo].[EventTypes] ([Id], [Name], [Code]) VALUES (8, N'Histology header created', N'008')
INSERT INTO [dbo].[EventTypes] ([Id], [Name], [Code]) VALUES (9, N'Histology focus created', N'009')
INSERT INTO [dbo].[EventTypes] ([Id], [Name], [Code]) VALUES (10, N'Histology header deleted', N'010')
INSERT INTO [dbo].[EventTypes] ([Id], [Name], [Code]) VALUES (11, N'Histology focus deleted', N'011')
INSERT INTO [dbo].[EventTypes] ([Id], [Name], [Code]) VALUES (12, N'Screening Outcomes uploaded', N'012')
INSERT INTO [dbo].[EventTypes] ([Id], [Name], [Code]) VALUES (13, N'Histology focus updated', N'013')
INSERT INTO [dbo].[EventTypes] ([Id], [Name], [Code]) VALUES (14, N'Histology header updated', N'014')
INSERT INTO [dbo].[EventTypes] ([Id], [Name], [Code]) VALUES (15, N'Volpara received', N'015')
SET IDENTITY_INSERT [dbo].[EventTypes] OFF

SET IDENTITY_INSERT [dbo].[HistologyLookups] ON
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (1, N'SIDE', N'Left')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (2, N'SIDE', N'Right')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (3, N'SIDE', N'Bilateral')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (4, N'TYPE', N'Screen')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (5, N'TYPE', N'Interval')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (6, N'SIDE', N' Unknown')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (7, N'TYPE', N' Unknown')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (8, N'DCIS', N' Unknown')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (9, N'DCIS', N'Low')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (10, N'DCIS', N'High')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (11, N'DCIS', N'Intermediate')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (12, N'DCIS', N'Intermediate + High')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (13, N'INVASIVE', N' Unknown')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (14, N'INVASIVE', N'Both')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (15, N'INVASIVE', N'CIS')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (16, N'INVASIVE', N'Invasive')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (22, N'VASCULAR', N' Unknown')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (23, N'VASCULAR', N'No')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (24, N'VASCULAR', N'Yes')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (25, N'VASCULAR', N'Probable')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (26, N'HER2', N' Unknown')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (27, N'HER2', N'0')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (28, N'HER2', N'1')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (29, N'HER2', N'2')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (30, N'HER2', N'2 Fish Amplified')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (31, N'HER2', N'2 Fish Not Amplified')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (32, N'HER2', N'3')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (34, N'DCIS', N'Low + High')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (35, N'DCIS', N'Low + Intermediate')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (36, N'INVTUMTYP', N'Invasive ductal carcinoma')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (37, N'INVTUMTYP', N'Invasive lobular carcinoma')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (38, N'INVTUMTYP', N'Invasive medullary-like carcinoma')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (39, N'INVTUMTYP', N'Invasive metaplastic carcinoma')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (40, N'INVTUMTYP', N'Invasive mucinous carcinoma')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (41, N'INVTUMTYP', N'Invasive tubular carcinoma')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (42, N'INVTUMTYP', N'Metastatic carcinoma')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (43, N'INVTUMTYP', N'Invasive other')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (44, N'INVTUMTYP', N'Mixed - Invasive ductal and lobular carcinoma')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (45, N'INVTUMTYP', N'Mixed - other')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (46, N'INVTUMTYP', N'None - in situ only')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (47, N'INSITUTYP', N'DCIS')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (48, N'INSITUTYP', N'LCIS')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (49, N'INSITUTYP', N'DCIS & LCIS')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (50, N'INSITUTYP', N'None - invasive only')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (51, N'INVTUMTYP', N' Unknown')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (52, N'INSITUTYP', N' Unknown')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (53, N'TNM-T', N'Tx')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (54, N'TNM-T', N'Tis')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (55, N'TNM-T', N'T1a')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (56, N'TNM-T', N'T1b')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (57, N'TNM-T', N'T1c')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (58, N'TNM-T', N'T2')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (59, N'TNM-T', N'T3')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (60, N'TNM-T', N'T4a')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (61, N'TNM-T', N'T4b')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (62, N'TNM-T', N'T4c')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (63, N'TNM-T', N'T4d')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (64, N'TNM-N', N'Nx')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (65, N'TNM-N', N'N0')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (66, N'TNM-N', N'N1mi')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (67, N'TNM-N', N'N1a')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (68, N'TNM-N', N'N1b')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (69, N'TNM-N', N'N1c')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (70, N'TNM-N', N'N2a')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (71, N'TNM-N', N'N2b')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (72, N'TNM-N', N'N3a')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (73, N'TNM-N', N'N3b')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (74, N'TNM-N', N'N3c')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (75, N'TNM-T', N' Unknown')
INSERT INTO [dbo].[HistologyLookups] ([Id], [LookupType], [LookupDescription]) VALUES (76, N'TNM-N', N' Unknown')
SET IDENTITY_INSERT [dbo].[HistologyLookups] OFF

SET IDENTITY_INSERT [dbo].[ParticipantLookups] ON
INSERT INTO [dbo].[ParticipantLookups] ([Id], [LookupType], [LookupDescription], [LookupCode]) VALUES (1, N'CHEMO', N'Not appropriate', N'CHEMONA')
INSERT INTO [dbo].[ParticipantLookups] ([Id], [LookupType], [LookupDescription], [LookupCode]) VALUES (2, N'CHEMO', N'Appropriate but prescription not filled', N'CHEMOAPPNOT')
INSERT INTO [dbo].[ParticipantLookups] ([Id], [LookupType], [LookupDescription], [LookupCode]) VALUES (3, N'CHEMO', N'Appropriate and prescription filled', N'CHEMOAPPFILL')
INSERT INTO [dbo].[ParticipantLookups] ([Id], [LookupType], [LookupDescription], [LookupCode]) VALUES (4, N'INITIAL', N'1. Technical recall', N'INI_TECH')
INSERT INTO [dbo].[ParticipantLookups] ([Id], [LookupType], [LookupDescription], [LookupCode]) VALUES (5, N'INITIAL', N'2. Recall for assessment', N'INI_ASSESS')
INSERT INTO [dbo].[ParticipantLookups] ([Id], [LookupType], [LookupDescription], [LookupCode]) VALUES (6, N'INITIAL', N'3. Routine recall', N'INI_ROUTINE')
INSERT INTO [dbo].[ParticipantLookups] ([Id], [LookupType], [LookupDescription], [LookupCode]) VALUES (7, N'TECH', N'Routine recall', N'TECH_ROUTINE')
INSERT INTO [dbo].[ParticipantLookups] ([Id], [LookupType], [LookupDescription], [LookupCode]) VALUES (8, N'TECH', N'DNA appointment', N'TECH_DNA')
INSERT INTO [dbo].[ParticipantLookups] ([Id], [LookupType], [LookupDescription], [LookupCode]) VALUES (9, N'TECH', N'Recall for assessment - routine recall', N'TECH_REC_ROUTINE')
INSERT INTO [dbo].[ParticipantLookups] ([Id], [LookupType], [LookupDescription], [LookupCode]) VALUES (10, N'TECH', N'Recall for assessment - breast cancer', N'TECH_REC_CANCER')
INSERT INTO [dbo].[ParticipantLookups] ([Id], [LookupType], [LookupDescription], [LookupCode]) VALUES (11, N'TECH', N'Recall for assessment - enhanced surveillance', N'TECH_REC_SURV')
INSERT INTO [dbo].[ParticipantLookups] ([Id], [LookupType], [LookupDescription], [LookupCode]) VALUES (12, N'RECALL', N'Routine recall', N'RECALL_ROUTINE')
INSERT INTO [dbo].[ParticipantLookups] ([Id], [LookupType], [LookupDescription], [LookupCode]) VALUES (13, N'RECALL', N'DNA appointment', N'RECALL_DNA')
INSERT INTO [dbo].[ParticipantLookups] ([Id], [LookupType], [LookupDescription], [LookupCode]) VALUES (14, N'RECALL', N'Breast cancer', N'RECALL_CANCER')
INSERT INTO [dbo].[ParticipantLookups] ([Id], [LookupType], [LookupDescription], [LookupCode]) VALUES (15, N'RECALL', N'Enhanced survelliance', N'RECALL_SURV')
INSERT INTO [dbo].[ParticipantLookups] ([Id], [LookupType], [LookupDescription], [LookupCode]) VALUES (16, N'RISKCONS', N'Face-to-face', N'RISK_FACE')
INSERT INTO [dbo].[ParticipantLookups] ([Id], [LookupType], [LookupDescription], [LookupCode]) VALUES (17, N'RISKCONS', N'Telephone', N'RISK_TELE')
SET IDENTITY_INSERT [dbo].[ParticipantLookups] OFF

SET IDENTITY_INSERT [dbo].[Questions] ON
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (1, N'heightInches', N'What is your approximate height (inches)?', 5)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (2, N'weightPounds', N'What is your approximate weight (pounds)?', 10)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (3, N'weightAt20', N'What was your approximate weight at age 20 (pounds)?', 15)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (4, N'racialBackground', N'Please select what best describes your ethnicity', 20)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (5, N'isAshkenazi', N'Are any of your ancestors of Jewish descent?', 25)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (6, N'otherBreastSurgery', N'Have you ever had breast surgery, including breast implants or a breast reduction, or do you currently have any nipple piecings?', 30)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (8, N'hadBreastBiopsy', N'Have you ever had a breast biopsy?', 60)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (9, N'BiopsyIncreasedRisk', N'Were you told that the diagnosis made on the removed breast tissue increased your risk of breast cancer?', 65)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (11, N'BiopsyResult', N'What was the result of your biopsy?', 70)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (12, N'startedMenstruating', N'Approximately how old were you when you had your first period?', 75)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (13, N'timesPregnant', N'How many pregnancies have you had that have continued into the third trimester (i.e. 28 weeks)?', 80)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (14, N'ageFirstChildBorn', N'How old were you when you had your first pregnancy that continued to at least 28 weeks (i.e. into the third trimester,)', 85)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (15, N'MenopausalStatus', N'What is your menopausal status?', 90)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (16, N'stoppedMenstruating', N'At approximately what age did you become post-menopausal?', 95)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (17, N'hadHysterectomy', N'Have you had a hysterectomy (removal of your uterus/womb)?', 100)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (18, N'hysterectomyAge', N'Approximately how old were you when you had your hysterectomy?', 110)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (19, N'MenopauseBeforeHysterectomy', N'Had you gone through the menopause before you had your hysterectomy?', 115)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (20, N'OvariesRemoved', N'Have either or both your ovaries been removed?', 120)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (21, N'OophUnilateralAge', N'How old were you when you had your ovary removed?', 125)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (22, N'OophBilateralAgeFirst', N'How old were you when you had your first ovary removed?', 130)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (23, N'OophBilternalAgeSecond', N'How old were you when you had your second ovary removed?', 135)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (24, N'MenopauseBeforeOoph', N'Had you gone through the menopause before you had your ovary(s) removed?', 140)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (26, N'hormoneUse', N'Have you ever used Hormone Replacement Therapy?', 145)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (27, N'HRTType', N'What HRT preparation are you taking or did you take? (If you have taken more than one type, please indicate the type taken for the longest time)', 150)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (28, N'HRTHowLong', N'Approximately how long have you been taking it/did you take it for?', 155)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (30, N'takenTamoxifen', N'Have you ever taken Tamoxifen?', 160)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (31, N'tamoxifenYears', N'Approximately how long have you been taking Tamoxifen?', 165)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (32, N'tamoxifenStopped', N'When did you stop taking Tamoxifen?', 1000)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (33, N'tamoxifenHowLong', N'Approximately how long did you take Tamoxifen for?', 1005)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (34, N'takenRaloxifene', N'Have you ever taken Raloxifene (Evista)?', 170)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (35, N'raloxifeneYears', N'Approximately how long have you been taking Raloxifene (Evista)?', 175)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (36, N'raloxifeneStopped', N'When did you stop taking Raloxifene (Evista)?', 1010)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (37, N'raloxifineHowLong', N'Approximately how long did you take Raloxifine (Evista) for?', 1015)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (38, N'takenAromataseInhibitor', N'Have you ever taken Anastrozole (Arimidex)?', 180)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (39, N'aromataseInhibitorYears', N'Approximately how long have you been taking Anastrozole (Arimidex)?', 185)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (40, N'anastrozoleStopped', N'When did you stop taking Anastrozole (Arimidex)?', 1020)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (41, N'anastrozoleHowLong', N'Approximately how long did you take Anastrozole (Arimidex) for?', 1025)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (43, N'ExcerciseYesNo', N'Have you done any moderate/vigorous activity during the past week? (Include activities where you feel warm/slightly out of breath, e.g. brisk walking, cycling, housework, DIY, gardening, other sports or work related activities)', 205)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (44, N'ExcerciseHrs', N'How much do you normally do in a typical week (hours)', 210)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (45, N'AlcoholYesNo', N'Do you drink alcohol?', 220)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (46, N'AlcoholHowMuch', N'How many units do you drink per week, on average', 225)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (47, N'hasSmoked', N'Have you ever smoked?', 230)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (48, N'startedSmoking', N'Approximately how old were you when you started smoking?', 1030)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (49, N'stoppedSmoking', N'Approximately how old were you when you stopped smoking (if previous smoker)', 1035)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (50, N'currentCigsPerDay', N'If current smoker how many cigarettes do you smoke per day?', 1040)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (51, N'previousCigsPerDay', N'If previous smoker how many cigarettes did you smoke per day?', 1045)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (52, N'EverBreastFeed', N'Did you ever breast-feed?', 245)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (54, N'UKClothingSize', N'What is your current UK clothes size for trousers/skirts? (e.g. size 10, 14, 20)', 270)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (55, N'birthControlUse', N'Do you use, or have you ever used an oral contraceptive pill?', 275)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (56, N'OCType', N'What type of oral contraceptives did you take?', 280)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (57, N'birthControlYears', N'Overall how long did you take the contraceptive pill for?', 285)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (60, N'birthControlContinuously', N'Did you use contraceptive continuously during this time?', 290)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (61, N'IUDWithHormones', N'Do you use or have you ever used an IUD that contains hormones (i.e. Mirena coil or Jaydess coil)?', 295)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (62, N'HowLongCurrentIUDYears', N'Overall how long did you use an IUD for (years)?', 300)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (63, N'PolycysticOvaries', N'Have you ever been diagnosed with polycystic ovaries?', 320)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (64, N'HasDiabetes', N'Have you ever been diagnosed with diabetes?', 325)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (65, N'breastImplants', N'Breast surgery type - Impants:', 35)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (66, N'breastImplantsSide', N'Breast surgery type - Implants side:', 37)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (67, N'breastReduction', N'Breast surgery type - Reduction:', 39)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (68, N'breastReductionSide', N'Breast surgery type - Reduction side:', 41)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (69, N'breastPiercings', N'Breast surgery type - Piercings:', 43)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (70, N'breastPiercingsSide', N'Breast surgery type - Piercings side:', 45)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (71, N'otherBreastSurgeryYesNo', N'Breast surgery type - Other:', 47)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (72, N'otherBreastSurgerySide', N'Breast surgery type - Other side:', 49)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (73, N'KnowFamilyHistory', N'Do you know your family history?', 190)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (74, N'RelativeHadGeneticTesting', N'Have any of your relatives had genetic testing in the past?', 195)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (75, N'AdditionalQuestions', N'Would you be willing to answer some additional questions?', 200)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (76, N'ExcerciseMins', N'How much do you normally do in a typical week (mins)', 215)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (77, N'SmokingHowLong', N'Approximately how many years have you been smoking?', 235)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (78, N'NumCigarettes', N'Approximately how many cigarettes per day?', 240)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (79, N'MonthsBreastFedChild1', N'Months breast fed child 1', 247)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (80, N'MonthsBreastFedChild2', N'Months breast fed child 2', 249)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (81, N'MonthsBreastFedChild3', N'Months breast fed child 3', 251)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (82, N'MonthsBreastFedChild4', N'Months breast fed child 4', 253)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (83, N'MonthsBreastFedChild5', N'Months breast fed child 5', 255)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (84, N'MonthsBreastFedChild6', N'Months breast fed child 6', 257)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (85, N'MonthsBreastFedChild7', N'Months breast fed child 7', 259)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (86, N'MonthsBreastFedChild8', N'Months breast fed child 8', 261)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (87, N'MonthsBreastFedChild9', N'Months breast fed child 9', 263)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (88, N'MonthsBreastFedChild10', N'Months breast fed child 10', 265)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (89, N'HowLongCurrentIUDMonths', N'Overall how long did you use an IUD for (months)?', 305)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (90, N'HowLongPastIUDYears', N'How long did you use the IUD with hormones (years)?', 310)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (91, N'HowLongPastIUDMonths', N'How long did you use the IUD with hormones (months)?', 315)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (92, N'Wibble', N'Answer to unmatched question - ', 700)
INSERT INTO [dbo].[Questions] ([Id], [Code], [Text], [QuestionNum]) VALUES (93, N'DoYouHaveOrHaveYouEverHadCancer', N'Do you have or have you ever had cancer?', 55)
SET IDENTITY_INSERT [dbo].[Questions] OFF

SET IDENTITY_INSERT [dbo].[ScreeningSites] ON
INSERT INTO [dbo].[ScreeningSites] ([Id], [Name], [Code], [AddressLine1], [AddressLine2], [AddressLine3], [AddressLine4], [PostCode], [LetterFrom], [Telephone], [LogoFooterLeft], [LogoFooterRight], [LogoHeaderRight], [LogoHeaderRightHeight], [LogoHeaderRightWidth], [LogoFooterLeftWidth], [LogoFooterRightWidth], [LogoFooterLeftHeight], [LogoFooterRightHeight], [Signature], [TrustCode]) VALUES (2, N'Wythenshawe', N'WYTH', N'Nightingale Centre', N'Wythenshawe Hospital', N'Southmoor Road', N'Manchester', N'M23 9LT', N'Prof. D. Gareth Evans', N'+44 (0)161 291 4409', N'MFT_INCORPORATING', N'MFT_DISABILITY', N'MFT_LOGO', N'1.71', N'5.5', N'13', N'2.34', N'1.75', N'2.34', N'trg', N'MFT')
INSERT INTO [dbo].[ScreeningSites] ([Id], [Name], [Code], [AddressLine1], [AddressLine2], [AddressLine3], [AddressLine4], [PostCode], [LetterFrom], [Telephone], [LogoFooterLeft], [LogoFooterRight], [LogoHeaderRight], [LogoHeaderRightHeight], [LogoHeaderRightWidth], [LogoFooterLeftWidth], [LogoFooterRightWidth], [LogoFooterLeftHeight], [LogoFooterRightHeight], [Signature], [TrustCode]) VALUES (3, N'Macclesfield', N'MACC', N'Breast Screening, New Alderley House', N'Macclesfield District General Hospital', N'Victoria Road', N'Macclesfield', N'SK10 3BL', N'Prof D. Gareth Evans', N'01625 661157', NULL, NULL, N'EAST_CHESHIRE_LOGO', N'2.47', N'5.5', NULL, NULL, NULL, NULL, NULL, N'EASTCHESHIRE')
INSERT INTO [dbo].[ScreeningSites] ([Id], [Name], [Code], [AddressLine1], [AddressLine2], [AddressLine3], [AddressLine4], [PostCode], [LetterFrom], [Telephone], [LogoFooterLeft], [LogoFooterRight], [LogoHeaderRight], [LogoHeaderRightHeight], [LogoHeaderRightWidth], [LogoFooterLeftWidth], [LogoFooterRightWidth], [LogoFooterLeftHeight], [LogoFooterRightHeight], [Signature], [TrustCode]) VALUES (5, N'Lancashire', N'LANCS', N'East Lancashire Breast Screening Service', N'Area 3, Burnley General Hospital', N'Casterton Avenue', N'Burnley', N'BB10 2PQ', N'Prof. D. Gareth Evans', N'01282805301', N'EAST_LANCS_SPE', NULL, N'EAST_LANCS_LOGO', N'1.64', N'5.5', N'11', NULL, N'1.16', NULL, NULL, N'EASTLANCS')
SET IDENTITY_INSERT [dbo].[ScreeningSites] OFF



