//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROCAS2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DashboardResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DashboardResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PROCAS2.Resources.DashboardResources", typeof(DashboardResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number consented:.
        /// </summary>
        public static string NUM_CONSENT {
            get {
                return ResourceManager.GetString("NUM_CONSENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number consented but without full details yet:.
        /// </summary>
        public static string NUM_CONSENT_NO_DETAILS {
            get {
                return ResourceManager.GetString("NUM_CONSENT_NO_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of invitees:.
        /// </summary>
        public static string NUM_PARC {
            get {
                return ResourceManager.GetString("NUM_PARC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter content received but not sent:.
        /// </summary>
        public static string NUM_RISK_NOT_SENT {
            get {
                return ResourceManager.GetString("NUM_RISK_NOT_SENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number waiting for risk letter from CRA:.
        /// </summary>
        public static string NUM_RISK_WAITING {
            get {
                return ResourceManager.GetString("NUM_RISK_WAITING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number yet to consent:.
        /// </summary>
        public static string NUM_YET_CONSENT {
            get {
                return ResourceManager.GetString("NUM_YET_CONSENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string SITE_CODE {
            get {
                return ResourceManager.GetString("SITE_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SITE_NAME {
            get {
                return ResourceManager.GetString("SITE_NAME", resourceCulture);
            }
        }
    }
}
