//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROCAS2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EventResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EventResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PROCAS2.Resources.EventResources", typeof(EventResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRA_Automatic.
        /// </summary>
        public static string CRA_AUTO_USER {
            get {
                return ResourceManager.GetString("CRA_AUTO_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 006.
        /// </summary>
        public static string EVENT_ASK_RISK {
            get {
                return ResourceManager.GetString("EVENT_ASK_RISK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk letter asked for (set by upload).
        /// </summary>
        public static string EVENT_ASK_RISK_STR {
            get {
                return ResourceManager.GetString("EVENT_ASK_RISK_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 002.
        /// </summary>
        public static string EVENT_CONSENT {
            get {
                return ResourceManager.GetString("EVENT_CONSENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consent received..
        /// </summary>
        public static string EVENT_CONSENT_STR {
            get {
                return ResourceManager.GetString("EVENT_CONSENT_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001.
        /// </summary>
        public static string EVENT_CREATED {
            get {
                return ResourceManager.GetString("EVENT_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant created..
        /// </summary>
        public static string EVENT_CREATED_STR {
            get {
                return ResourceManager.GetString("EVENT_CREATED_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 005.
        /// </summary>
        public static string EVENT_DELETED {
            get {
                return ResourceManager.GetString("EVENT_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string EVENT_DELETED_STR {
            get {
                return ResourceManager.GetString("EVENT_DELETED_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 008.
        /// </summary>
        public static string EVENT_HISTCREATED {
            get {
                return ResourceManager.GetString("EVENT_HISTCREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histology header primary  {0} created..
        /// </summary>
        public static string EVENT_HISTCREATED_STR {
            get {
                return ResourceManager.GetString("EVENT_HISTCREATED_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 010.
        /// </summary>
        public static string EVENT_HISTDELETED {
            get {
                return ResourceManager.GetString("EVENT_HISTDELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histology header primary {0} deleted..
        /// </summary>
        public static string EVENT_HISTDELETED_STR {
            get {
                return ResourceManager.GetString("EVENT_HISTDELETED_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 009.
        /// </summary>
        public static string EVENT_HISTFOCUSCREATED {
            get {
                return ResourceManager.GetString("EVENT_HISTFOCUSCREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histology focus {0} primary {1} created..
        /// </summary>
        public static string EVENT_HISTFOCUSCREATED_STR {
            get {
                return ResourceManager.GetString("EVENT_HISTFOCUSCREATED_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 011.
        /// </summary>
        public static string EVENT_HISTFOCUSDELETED {
            get {
                return ResourceManager.GetString("EVENT_HISTFOCUSDELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histology focus {0} primary {1} deleted..
        /// </summary>
        public static string EVENT_HISTFOCUSDELETED_STR {
            get {
                return ResourceManager.GetString("EVENT_HISTFOCUSDELETED_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 013.
        /// </summary>
        public static string EVENT_HISTFOCUSUPDATED {
            get {
                return ResourceManager.GetString("EVENT_HISTFOCUSUPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histology focus {0}  primary {1} updated.
        /// </summary>
        public static string EVENT_HISTFOCUSUPDATED_STR {
            get {
                return ResourceManager.GetString("EVENT_HISTFOCUSUPDATED_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 014.
        /// </summary>
        public static string EVENT_HISTUPDATED {
            get {
                return ResourceManager.GetString("EVENT_HISTUPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histology header primary {0} updated.
        /// </summary>
        public static string EVENT_HISTUPDATED_STR {
            get {
                return ResourceManager.GetString("EVENT_HISTUPDATED_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 004.
        /// </summary>
        public static string EVENT_PROPERTY_UPDATED {
            get {
                return ResourceManager.GetString("EVENT_PROPERTY_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} updated from {{{1}}} to {{{2}}}.
        /// </summary>
        public static string EVENT_PROPERTY_UPDATED_STR {
            get {
                return ResourceManager.GetString("EVENT_PROPERTY_UPDATED_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 007.
        /// </summary>
        public static string EVENT_RISKLETTER {
            get {
                return ResourceManager.GetString("EVENT_RISKLETTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk letter received..
        /// </summary>
        public static string EVENT_RISKLETTER_STR {
            get {
                return ResourceManager.GetString("EVENT_RISKLETTER_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 012.
        /// </summary>
        public static string EVENT_SCREENING_OUTCOME {
            get {
                return ResourceManager.GetString("EVENT_SCREENING_OUTCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screening Outcomes Uploaded.
        /// </summary>
        public static string EVENT_SCREENING_OUTCOME_STR {
            get {
                return ResourceManager.GetString("EVENT_SCREENING_OUTCOME_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 003.
        /// </summary>
        public static string EVENT_UPDATED {
            get {
                return ResourceManager.GetString("EVENT_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full details added..
        /// </summary>
        public static string EVENT_UPDATED_STR {
            get {
                return ResourceManager.GetString("EVENT_UPDATED_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 015.
        /// </summary>
        public static string EVENT_VOLPARA {
            get {
                return ResourceManager.GetString("EVENT_VOLPARA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volpara Screening received.
        /// </summary>
        public static string EVENT_VOLPARA_STR {
            get {
                return ResourceManager.GetString("EVENT_VOLPARA_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volpara_Automatic.
        /// </summary>
        public static string VOLPARA_AUTO_USER {
            get {
                return ResourceManager.GetString("VOLPARA_AUTO_USER", resourceCulture);
            }
        }
    }
}
