//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROCAS2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExportResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExportResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PROCAS2.Resources.ExportResources", typeof(ExportResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate all that are ready.
        /// </summary>
        public static string ALL_READY {
            get {
                return ResourceManager.GetString("ALL_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0161 291 4408.
        /// </summary>
        public static string BCPREDICT_PHONE {
            get {
                return ResourceManager.GetString("BCPREDICT_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;nbsp;.
        /// </summary>
        public static string BLANK_LINE {
            get {
                return ResourceManager.GetString("BLANK_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ms..
        /// </summary>
        public static string DEFAULT_TITLE {
            get {
                return ResourceManager.GetString("DEFAULT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAiYAAAD/CAIAAABKAorfAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAZdEVYdFNvZnR3YXJlAHBhaW50Lm5ldCA0LjAuMjHxIGmVAACxYUlEQVR4XuxdBXxUx9eFuuPa0kJxd3d3Jy4kEAiBEIJrILi7u7vHNu7u7u7ubt935s1mm2xsN6S06X/O73a7bObN3LF77p03b16z/2NgYGBgYPgsYJTDwMDAwPCZwCiHgYGBgeEzgVEOAwMDA8NnAqMcBgYGBobPBEY5DAwMDAyfCYxyGBgYGBg+ExjlMDA0GZSVlReXlBUWl+UXlVIpYMLk3yoYn3mF5EtJaTkFxjCjHAaGJoPC4tKU7KLolPyQhNzA+JzguJyQ+FwmTP6dEhyfExCbE56Ym5lbTFkHY5hRDgNDk0FKVqG5X+odi+gjH0MPvAk++Db44LsQJkz+pfI2eP+L [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EAST_CHESHIRE_LOGO {
            get {
                return ResourceManager.GetString("EAST_CHESHIRE_LOGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAA7oAAAEcCAIAAABmvF/gAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAZdEVYdFNvZnR3YXJlAHBhaW50Lm5ldCA0LjAuMjHxIGmVAACtH0lEQVR4Xu29268f1ZXvu/+Axr1Pq+lInaSfOp3z0uTyErYSkR1aSqQQeCAPXFa2OjHRBm8JAw8b7IedNBBMEx0cHSIlaxF8Ak4wdIM5GBwJusG0GmPAdr9gIi7Sxl7Ey+TlhCTQ5KH9+3HGbY455qUuv/rVWvYPhvRRrVmz5hxzzDFnVX2rVv2q/tP7708dx3Ecx1k8ppOY0LTjOKNgdiuXy47jOI7zgWByOs9xHGcwrJVp6XLZcRzHcRYWc0Z3HGd8YOeaTlwuO47jOM5iElTyyq5D//Uby47jjM/SMuxiLpcdx3EcZ7G5+57n8nO84zgjAbuYy2XHcRzHWWxcLjvO+gG7 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EAST_LANCS_LOGO {
            get {
                return ResourceManager.GetString("EAST_LANCS_LOGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAACyAAAAEsCAIAAAAOjKEoAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAALh8AAC4fAXjugV8AAAAZdEVYdFNvZnR3YXJlAHBhaW50Lm5ldCA0LjAuMTM0A1t6AADTHklEQVR4Xuy9B3hc1Zn//w+k7aZuSXaTbDa7m/x2N9swBLAB0wlOKAm2MWA62MY2NtiAAeOCwYAxGMu9SJbcu2zLtrqs3nvvvffeR1P8v4kOjnhlazQz55x779zv5/k8eYgs3fe9RzN3Rvd855z/7zIAAAAAAAAAAAAAAAAAAAAAAAAAAJgQBCwAAAC4LT0mc9ugaax9Ixb2bwAAAAAAAAAABKD82UX+EFP+NGP/BgAAAAAAAAA6BwELAAAAbsuFslaPtOqxRtV2sH8DAAAAAAAAACAA5c8u8oeY8qcZ+zcAAAAAAAAA0DkIWAAAAHBbELAAAAAAAAAAAMkgYAEAAAAAAABw [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EAST_LANCS_SPE {
            get {
                return ResourceManager.GetString("EAST_LANCS_SPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string EXPORT_OR {
            get {
                return ResourceManager.GetString("EXPORT_OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The University of Manchester.
        /// </summary>
        public static string FROM_ADDRESS_1 {
            get {
                return ResourceManager.GetString("FROM_ADDRESS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oxford Road.
        /// </summary>
        public static string FROM_ADDRESS_2 {
            get {
                return ResourceManager.GetString("FROM_ADDRESS_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manchester.
        /// </summary>
        public static string FROM_ADDRESS_3 {
            get {
                return ResourceManager.GetString("FROM_ADDRESS_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;nbsp;.
        /// </summary>
        public static string FROM_ADDRESS_4 {
            get {
                return ResourceManager.GetString("FROM_ADDRESS_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BC-Predict.
        /// </summary>
        public static string FROM_ORG {
            get {
                return ResourceManager.GetString("FROM_ORG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M13 9PL.
        /// </summary>
        public static string FROM_POSTCODE {
            get {
                return ResourceManager.GetString("FROM_POSTCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /9j/4RTnRXhpZgAATU0AKgAAAAgABwESAAMAAAABAAEAAAEaAAUAAAABAAAAYgEbAAUAAAABAAAAagEoAAMAAAABAAIAAAExAAIAAAAgAAAAcgEyAAIAAAAUAAAAkodpAAQAAAABAAAAqAAAANQALcbAAAAnEAAtxsAAACcQQWRvYmUgUGhvdG9zaG9wIENTNS4xIE1hY2ludG9zaAAyMDEyOjA0OjE5IDE4OjU2OjA4AAAAAAOgAQADAAAAAQABAACgAgAEAAAAAQAAAh+gAwAEAAAAAQAAAOYAAAAAAAAABgEDAAMAAAABAAYAAAEaAAUAAAABAAABIgEbAAUAAAABAAABKgEoAAMAAAABAAIAAAIBAAQAAAABAAABMgICAAQAAAABAAATrQAAAAAAAABIAAAAAQAAAEgAAAAB/9j/7QAMQWRvYmVfQ00AAf/uAA5BZG9iZQBkgAAAAAH/2wCEAAwICAgJCAwJCQwRCwoLERUPDAwPFRgTExUTExgR [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LOGO_IMAGE {
            get {
                return ResourceManager.GetString("LOGO_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAkQAAACkCAIAAAD5WaamAAAAIGNIUk0AAHolAACAgwAA+f8AAIDpAAB1MAAA6mAAADqYAAAXb5JfxUYAAAAJcEhZcwAACxIAAAsSAdLdfvwAADmUaVRYdFhNTDpjb20uYWRvYmUueG1wAAAAAAA8P3hwYWNrZXQgYmVnaW49Iu+7vyIgaWQ9Ilc1TTBNcENlaGlIenJlU3pOVGN6a2M5ZCI/Pgo8eDp4bXBtZXRhIHhtbG5zOng9ImFkb2JlOm5zOm1ldGEvIiB4OnhtcHRrPSJBZG9iZSBYTVAgQ29yZSA1LjYtYzEzOCA3OS4xNTk4MjQsIDIwMTYvMDkvMTQtMDE6MDk6MDEgICAgICAgICI+CiAgIDxyZGY6UkRGIHhtbG5zOnJkZj0iaHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3ludGF4LW5zIyI+CiAgICAgIDxyZGY6RGVzY3JpcHRpb24g [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MFT_DISABILITY {
            get {
                return ResourceManager.GetString("MFT_DISABILITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAqEAAABaCAMAAAC/tn+fAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAMAUExURYCAgICAl4CXl5eAgJeAl5eXgJeXl4CArYCXrZeArZeXrZetra2AgK2Al62XgK2Xl62Ara2tgK2tl62trYCXwpeXwoCtwoCt1pet1q2Xwq2t1pfCwpfC1pfC663Cwq3W1q3C663W663W/8KXgMKXl8KXrcKtgNatgNatl8KtwsLCl9bCl8LCrdbWrevCl+vWrf/WrcLWwsLr1tbrwtb/1sLr68Lr/9b/69b//+vrwuv/1v/rwv//1uv/6+v/////6////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MFT_INCORPORATING {
            get {
                return ResourceManager.GetString("MFT_INCORPORATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAicAAACrCAYAAAC9vTxXAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAEAtSURBVHhe7Z0J3D7V+P//LVRKyPJX0i+UNUWE0CI/tBCiEEaWiLRYIjsRibIVqZCU7GsMZd8TkSXZd7Lzs28/v8/nmWue58yZ65w5Z2ae+76f6Xq/Xp/X9/vMuc41c88998w1Z7nO/zMMwzAmQFG+FPqPyTQJGYZhGBPAghPTlGQYhmFMAAtOTFOSYRiGMQEsODFNSYZhGMYEsODENCUZhmEYE8CCE9OUZBiGYUwAC05M4+kn0LnQidDh0H7QrtB20NaedoBuAd0BujN0APRo6BjoddBHoMsgbT9hGYZhGBNgvODkZpD/AOqrPSFtH0PEh6C2ry7tAmn+LoA0+1SdCWl++2hnSNtHihhAaD5T9DPo1RADi2vJFTUuRbkZxOvhORDP+f9C2rFUMgzDMCbAOMHJpeJtHIpyHYgPPm1f [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MFT_LOGO {
            get {
                return ResourceManager.GetString("MFT_LOGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHS Number.
        /// </summary>
        public static string NHS_NUMBER {
            get {
                return ResourceManager.GetString("NHS_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The NHS Number does not exist in the database..
        /// </summary>
        public static string NHS_NUMBER_INVALID {
            get {
                return ResourceManager.GetString("NHS_NUMBER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The full details of this participant have not been uploaded yet..
        /// </summary>
        public static string NO_DETAILS_YET {
            get {
                return ResourceManager.GetString("NO_DETAILS_YET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This participant has not received a risk letter yet..
        /// </summary>
        public static string NO_LETTER_YET {
            get {
                return ResourceManager.GetString("NO_LETTER_YET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This participant has not consented yet..
        /// </summary>
        public static string NOT_CONSENTED {
            get {
                return ResourceManager.GetString("NOT_CONSENTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content/images/uni.png.
        /// </summary>
        public static string PROCAS2_IMAGE {
            get {
                return ResourceManager.GetString("PROCAS2_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.67.
        /// </summary>
        public static string PROCAS2_LOGO_HEIGHT_CM {
            get {
                return ResourceManager.GetString("PROCAS2_LOGO_HEIGHT_CM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.5.
        /// </summary>
        public static string PROCAS2_LOGO_WIDTH_CM {
            get {
                return ResourceManager.GetString("PROCAS2_LOGO_WIDTH_CM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref:.
        /// </summary>
        public static string REF {
            get {
                return ResourceManager.GetString("REF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INSERT CONSENT DATE].
        /// </summary>
        public static string REPLACE_CONSENT_DATE {
            get {
                return ResourceManager.GetString("REPLACE_CONSENT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INSERT HOSPITAL].
        /// </summary>
        public static string REPLACE_HOSPITALNAME {
            get {
                return ResourceManager.GetString("REPLACE_HOSPITALNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INSERT LOCAL SCREENING OFFICE NUMBER].
        /// </summary>
        public static string REPLACE_HOSPITALNUMBER {
            get {
                return ResourceManager.GetString("REPLACE_HOSPITALNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INSERT NHS NUMBER].
        /// </summary>
        public static string REPLACE_NHS_NUMBER {
            get {
                return ResourceManager.GetString("REPLACE_NHS_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [INSERT PATIENT NAME].
        /// </summary>
        public static string REPLACE_PATIENTNAME {
            get {
                return ResourceManager.GetString("REPLACE_PATIENTNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear.
        /// </summary>
        public static string SALUTATION {
            get {
                return ResourceManager.GetString("SALUTATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        public static string SENT_DATE {
            get {
                return ResourceManager.GetString("SENT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed,.
        /// </summary>
        public static string SIGN_OFF {
            get {
                return ResourceManager.GetString("SIGN_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAI4AAAAdCAYAAAB8D1TlAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAF3SURBVHhe7dJBbsUgDATQ3P/Srf4CaeQ/xgbcJoR50iwSGwKEK+kniMgXdlG8iKQvRbZPDjBzGUb75WVWLsDKWNlYxY+vmEM2U/XDdXEOo4sj02Z/ehsX5Q3YvjBvFO7RLRA40UxWsTm9ZLBxVXkStr7RfHELACfANPa5wV6vx8PG3hkP68VUYXP/Z6heEQeznl4NZXoanNMmg43z8hfYd+5OhI1pcdkGHGRrKKojrw/nsNkd29NKKrH5WbrYAAzCZ1b3eHN5kTrsfFmmRJPYmn2OYL+NzGPnmc2yzGTYg8liYz+Rcewco5Qb+Ui2T2rZc7e5BX48WkirR32SZ880m1uxRXgLw/dej+S08xvJo7BF9d6196xH+v [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SIGNATURE {
            get {
                return ResourceManager.GetString("SIGNATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trust To Export?.
        /// </summary>
        public static string SITE_TO_PROCESS {
            get {
                return ResourceManager.GetString("SITE_TO_PROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel:.
        /// </summary>
        public static string TELEPHONE {
            get {
                return ResourceManager.GetString("TELEPHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East Cheshire NHS Trust.
        /// </summary>
        public static string TRUST_EASTCHESHIRE {
            get {
                return ResourceManager.GetString("TRUST_EASTCHESHIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to East Lancashire Hospitals NHS Trust.
        /// </summary>
        public static string TRUST_EASTLANCS {
            get {
                return ResourceManager.GetString("TRUST_EASTLANCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manchester University NHS Trust.
        /// </summary>
        public static string TRUST_MFT {
            get {
                return ResourceManager.GetString("TRUST_MFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAKoAAAA/CAYAAABw3VNyAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAZdEVYdFNvZnR3YXJlAHBhaW50Lm5ldCA0LjAuMjHxIGmVAAAQr0lEQVR4Xu2d/XNU1RnHdzeBWh0RiCICSggBZRw7dfyljmN/qB07YDtOnY6/tFbHTju2IqKtrQokJCSExLyhoK12alu1o31RQR1HxjrTqu3PnUKSTch7AmTzBvoHPP1+z9ljbu4+e3M3UF3C+eEzu/vc85a93/Oc57zcTUJEPJ6iRzV6PMWGavR4ig3V6PEUG6rR4yk2VKPHU2yoRo+n2FCNHk+xoRo9nmJDNXo8xYZq9HiKDdXo8RQbqtHjKTZUo+fCpnfrezKy+S0ZqTgow8ubZbisWUbWPysjWw5Lz7Z3kUTP9/9ENXouLAa2viVdmw5IT7JWRhK7ZRScSOyRU4kmySSa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string UNI_LOGO {
            get {
                return ResourceManager.GetString("UNI_LOGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost:53074.
        /// </summary>
        public static string URL_DEV {
            get {
                return ResourceManager.GetString("URL_DEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://procas2-collator.azurewebsites.net.
        /// </summary>
        public static string URL_PROD {
            get {
                return ResourceManager.GetString("URL_PROD", resourceCulture);
            }
        }
    }
}
