//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROCAS2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExportResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExportResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PROCAS2.Resources.ExportResources", typeof(ExportResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate all that are ready.
        /// </summary>
        public static string ALL_READY {
            get {
                return ResourceManager.GetString("ALL_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;nbsp;.
        /// </summary>
        public static string BLANK_LINE {
            get {
                return ResourceManager.GetString("BLANK_LINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ms..
        /// </summary>
        public static string DEFAULT_TITLE {
            get {
                return ResourceManager.GetString("DEFAULT_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string EXPORT_OR {
            get {
                return ResourceManager.GetString("EXPORT_OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The University of Manchester.
        /// </summary>
        public static string FROM_ADDRESS_1 {
            get {
                return ResourceManager.GetString("FROM_ADDRESS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oxford Road.
        /// </summary>
        public static string FROM_ADDRESS_2 {
            get {
                return ResourceManager.GetString("FROM_ADDRESS_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manchester.
        /// </summary>
        public static string FROM_ADDRESS_3 {
            get {
                return ResourceManager.GetString("FROM_ADDRESS_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;nbsp;.
        /// </summary>
        public static string FROM_ADDRESS_4 {
            get {
                return ResourceManager.GetString("FROM_ADDRESS_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BC-Predict.
        /// </summary>
        public static string FROM_ORG {
            get {
                return ResourceManager.GetString("FROM_ORG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M13 9PL.
        /// </summary>
        public static string FROM_POSTCODE {
            get {
                return ResourceManager.GetString("FROM_POSTCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /9j/4RTnRXhpZgAATU0AKgAAAAgABwESAAMAAAABAAEAAAEaAAUAAAABAAAAYgEbAAUAAAABAAAAagEoAAMAAAABAAIAAAExAAIAAAAgAAAAcgEyAAIAAAAUAAAAkodpAAQAAAABAAAAqAAAANQALcbAAAAnEAAtxsAAACcQQWRvYmUgUGhvdG9zaG9wIENTNS4xIE1hY2ludG9zaAAyMDEyOjA0OjE5IDE4OjU2OjA4AAAAAAOgAQADAAAAAQABAACgAgAEAAAAAQAAAh+gAwAEAAAAAQAAAOYAAAAAAAAABgEDAAMAAAABAAYAAAEaAAUAAAABAAABIgEbAAUAAAABAAABKgEoAAMAAAABAAIAAAIBAAQAAAABAAABMgICAAQAAAABAAATrQAAAAAAAABIAAAAAQAAAEgAAAAB/9j/7QAMQWRvYmVfQ00AAf/uAA5BZG9iZQBkgAAAAAH/2wCEAAwICAgJCAwJCQwRCwoLERUPDAwPFRgTExUTExgR [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LOGO_IMAGE {
            get {
                return ResourceManager.GetString("LOGO_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAkQAAACkCAIAAAD5WaamAAAAIGNIUk0AAHolAACAgwAA+f8AAIDpAAB1MAAA6mAAADqYAAAXb5JfxUYAAAAJcEhZcwAACxIAAAsSAdLdfvwAADmUaVRYdFhNTDpjb20uYWRvYmUueG1wAAAAAAA8P3hwYWNrZXQgYmVnaW49Iu+7vyIgaWQ9Ilc1TTBNcENlaGlIenJlU3pOVGN6a2M5ZCI/Pgo8eDp4bXBtZXRhIHhtbG5zOng9ImFkb2JlOm5zOm1ldGEvIiB4OnhtcHRrPSJBZG9iZSBYTVAgQ29yZSA1LjYtYzEzOCA3OS4xNTk4MjQsIDIwMTYvMDkvMTQtMDE6MDk6MDEgICAgICAgICI+CiAgIDxyZGY6UkRGIHhtbG5zOnJkZj0iaHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3ludGF4LW5zIyI+CiAgICAgIDxyZGY6RGVzY3JpcHRpb24g [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MFT_DISABILITY {
            get {
                return ResourceManager.GetString("MFT_DISABILITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAqEAAABaCAMAAAC/tn+fAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAMAUExURYCAgICAl4CXl5eAgJeAl5eXgJeXl4CArYCXrZeArZeXrZetra2AgK2Al62XgK2Xl62Ara2tgK2tl62trYCXwpeXwoCtwoCt1pet1q2Xwq2t1pfCwpfC1pfC663Cwq3W1q3C663W663W/8KXgMKXl8KXrcKtgNatgNatl8KtwsLCl9bCl8LCrdbWrevCl+vWrf/WrcLWwsLr1tbrwtb/1sLr68Lr/9b/69b//+vrwuv/1v/rwv//1uv/6+v/////6////wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MFT_INCORPORATING {
            get {
                return ResourceManager.GetString("MFT_INCORPORATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAicAAACrCAYAAAC9vTxXAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAEAtSURBVHhe7Z0J3D7V+P//LVRKyPJX0i+UNUWE0CI/tBCiEEaWiLRYIjsRibIVqZCU7GsMZd8TkSXZd7Lzs28/v8/nmWue58yZ65w5Z2ae+76f6Xq/Xp/X9/vMuc41c88998w1Z7nO/zMMwzAmQFG+FPqPyTQJGYZhGBPAghPTlGQYhmFMAAtOTFOSYRiGMQEsODFNSYZhGMYEsODENCUZhmEYE8CCE9OUZBiGYUwAC05M4+kn0LnQidDh0H7QrtB20NaedoBuAd0BujN0APRo6BjoddBHoMsgbT9hGYZhGBNgvODkZpD/AOqrPSFtH0PEh6C2ry7tAmn+LoA0+1SdCWl++2hnSNtHihhAaD5T9DPo1RADi2vJFTUuRbkZxOvhORDP+f9C2rFUMgzDMCbAOMHJpeJtHIpyHYgPPm1f [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MFT_LOGO {
            get {
                return ResourceManager.GetString("MFT_LOGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.71.
        /// </summary>
        public static string MFT_LOGO_HEIGHT {
            get {
                return ResourceManager.GetString("MFT_LOGO_HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.5.
        /// </summary>
        public static string MFT_LOGO_WIDTH {
            get {
                return ResourceManager.GetString("MFT_LOGO_WIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHS Number.
        /// </summary>
        public static string NHS_NUMBER {
            get {
                return ResourceManager.GetString("NHS_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The NHS Number does not exist in the database..
        /// </summary>
        public static string NHS_NUMBER_INVALID {
            get {
                return ResourceManager.GetString("NHS_NUMBER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The full details of this participant have not been uploaded yet..
        /// </summary>
        public static string NO_DETAILS_YET {
            get {
                return ResourceManager.GetString("NO_DETAILS_YET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This participant has not received a risk letter yet..
        /// </summary>
        public static string NO_LETTER_YET {
            get {
                return ResourceManager.GetString("NO_LETTER_YET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This participant has not consented yet..
        /// </summary>
        public static string NOT_CONSENTED {
            get {
                return ResourceManager.GetString("NOT_CONSENTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content/images/uni.png.
        /// </summary>
        public static string PROCAS2_IMAGE {
            get {
                return ResourceManager.GetString("PROCAS2_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.5.
        /// </summary>
        public static string PROCAS2_LOGO_HEIGHT_CM {
            get {
                return ResourceManager.GetString("PROCAS2_LOGO_HEIGHT_CM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.5.
        /// </summary>
        public static string PROCAS2_LOGO_WIDTH_CM {
            get {
                return ResourceManager.GetString("PROCAS2_LOGO_WIDTH_CM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear.
        /// </summary>
        public static string SALUTATION {
            get {
                return ResourceManager.GetString("SALUTATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        public static string SENT_DATE {
            get {
                return ResourceManager.GetString("SENT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed,.
        /// </summary>
        public static string SIGN_OFF {
            get {
                return ResourceManager.GetString("SIGN_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel:.
        /// </summary>
        public static string TELEPHONE {
            get {
                return ResourceManager.GetString("TELEPHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iVBORw0KGgoAAAANSUhEUgAAAKkAAABICAYAAACNzdUIAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAEpRAABKUQB8xayBAAAABh0RVh0U29mdHdhcmUAQWRvYmUgRmlyZXdvcmtzT7MfTgAAEEFwclZXeJztWguUVOV9v7uzD+cycHcvZPcOO3NhdrnDXVigdU1FU/MgHnNMWo9aMEF5CMiCsETER4TwEHnOzM5jl11wFVwggAESRE2CGo0b0yatjjYmbRK1tcdkc3LS5uRx2tNWa/r19/++/8zcGXkt5Awnp3t3fvO9v//7/3134OX//dZvtNXaZwQ9WSE0+spmRbZdZDWqoiGRzfZns+1ZdPYLqvb3Z/s7sv3t2Y5stqMj29FOfeiV6O/v6O9vp3GUHR39GG3HXPR1UAsPBlHXsh1af4fW0Y5xLduu4btjmdgZul30zFgluttW5pFp6/TUJYYy+fFOhWmdItF8h9h//Sbx9uAPRXryMrFl7Fzxvb6v [rest of string was truncated]&quot;;.
        /// </summary>
        public static string UNI_LOGO {
            get {
                return ResourceManager.GetString("UNI_LOGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost:53074.
        /// </summary>
        public static string URL_DEV {
            get {
                return ResourceManager.GetString("URL_DEV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://procas2-collator.azurewebsites.net.
        /// </summary>
        public static string URL_PROD {
            get {
                return ResourceManager.GetString("URL_PROD", resourceCulture);
            }
        }
    }
}
