//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROCAS2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExportResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExportResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PROCAS2.Resources.ExportResources", typeof(ExportResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate all that are ready.
        /// </summary>
        public static string ALL_READY {
            get {
                return ResourceManager.GetString("ALL_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string EXPORT_OR {
            get {
                return ResourceManager.GetString("EXPORT_OR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The University of Manchester.
        /// </summary>
        public static string FROM_ADDRESS_1 {
            get {
                return ResourceManager.GetString("FROM_ADDRESS_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oxford Road.
        /// </summary>
        public static string FROM_ADDRESS_2 {
            get {
                return ResourceManager.GetString("FROM_ADDRESS_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manchester.
        /// </summary>
        public static string FROM_ADDRESS_3 {
            get {
                return ResourceManager.GetString("FROM_ADDRESS_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string FROM_ADDRESS_4 {
            get {
                return ResourceManager.GetString("FROM_ADDRESS_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROCAS2.
        /// </summary>
        public static string FROM_ORG {
            get {
                return ResourceManager.GetString("FROM_ORG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M13 9PL.
        /// </summary>
        public static string FROM_POSTCODE {
            get {
                return ResourceManager.GetString("FROM_POSTCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /9j/4RTnRXhpZgAATU0AKgAAAAgABwESAAMAAAABAAEAAAEaAAUAAAABAAAAYgEbAAUAAAABAAAAagEoAAMAAAABAAIAAAExAAIAAAAgAAAAcgEyAAIAAAAUAAAAkodpAAQAAAABAAAAqAAAANQALcbAAAAnEAAtxsAAACcQQWRvYmUgUGhvdG9zaG9wIENTNS4xIE1hY2ludG9zaAAyMDEyOjA0OjE5IDE4OjU2OjA4AAAAAAOgAQADAAAAAQABAACgAgAEAAAAAQAAAh+gAwAEAAAAAQAAAOYAAAAAAAAABgEDAAMAAAABAAYAAAEaAAUAAAABAAABIgEbAAUAAAABAAABKgEoAAMAAAABAAIAAAIBAAQAAAABAAABMgICAAQAAAABAAATrQAAAAAAAABIAAAAAQAAAEgAAAAB/9j/7QAMQWRvYmVfQ00AAf/uAA5BZG9iZQBkgAAAAAH/2wCEAAwICAgJCAwJCQwRCwoLERUPDAwPFRgTExUTExgR [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LOGO_IMAGE {
            get {
                return ResourceManager.GetString("LOGO_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHS Number.
        /// </summary>
        public static string NHS_NUMBER {
            get {
                return ResourceManager.GetString("NHS_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The NHS Number does not exist in the database..
        /// </summary>
        public static string NHS_NUMBER_INVALID {
            get {
                return ResourceManager.GetString("NHS_NUMBER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The full details of this participant have not been uploaded yet..
        /// </summary>
        public static string NO_DETAILS_YET {
            get {
                return ResourceManager.GetString("NO_DETAILS_YET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This participant has not received a risk letter yet..
        /// </summary>
        public static string NO_LETTER_YET {
            get {
                return ResourceManager.GetString("NO_LETTER_YET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This participant has not consented yet..
        /// </summary>
        public static string NOT_CONSENTED {
            get {
                return ResourceManager.GetString("NOT_CONSENTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear.
        /// </summary>
        public static string SALUTATION {
            get {
                return ResourceManager.GetString("SALUTATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yours sincerely,.
        /// </summary>
        public static string SIGN_OFF {
            get {
                return ResourceManager.GetString("SIGN_OFF", resourceCulture);
            }
        }
    }
}
