//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROCAS2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HistologyResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HistologyResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PROCAS2.Resources.HistologyResources", typeof(HistologyResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string COMMENTS {
            get {
                return ResourceManager.GetString("COMMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please create the Histology record header before entering focus records..
        /// </summary>
        public static string CREATE_HEADER_PLEASE {
            get {
                return ResourceManager.GetString("CREATE_HEADER_PLEASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCIS Only Grade.
        /// </summary>
        public static string DCIS_GRADE {
            get {
                return ResourceManager.GetString("DCIS_GRADE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histology Details.
        /// </summary>
        public static string DETAILS {
            get {
                return ResourceManager.GetString("DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis Date.
        /// </summary>
        public static string DIAGNOSIS_DATE {
            get {
                return ResourceManager.GetString("DIAGNOSIS_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-Focal?.
        /// </summary>
        public static string DIAGNOSIS_MULTI_FOCAL {
            get {
                return ResourceManager.GetString("DIAGNOSIS_MULTI_FOCAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis Side.
        /// </summary>
        public static string DIAGNOSIS_SIDE {
            get {
                return ResourceManager.GetString("DIAGNOSIS_SIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosis Type.
        /// </summary>
        public static string DIAGNOSIS_TYPE {
            get {
                return ResourceManager.GetString("DIAGNOSIS_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ER Score.
        /// </summary>
        public static string ER_SCORE {
            get {
                return ResourceManager.GetString("ER_SCORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ER Status.
        /// </summary>
        public static string ER_STATUS {
            get {
                return ResourceManager.GetString("ER_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Primary Breast Cancer Histology.
        /// </summary>
        public static string FIRST_PRIMARY {
            get {
                return ResourceManager.GetString("FIRST_PRIMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus Edit.
        /// </summary>
        public static string FOCUS {
            get {
                return ResourceManager.GetString("FOCUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus Number.
        /// </summary>
        public static string FOCUS_NUMBER {
            get {
                return ResourceManager.GetString("FOCUS_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The changes to the header have been saved..
        /// </summary>
        public static string HEADER_SAVED {
            get {
                return ResourceManager.GetString("HEADER_SAVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HER2 Score.
        /// </summary>
        public static string HER2_SCORE {
            get {
                return ResourceManager.GetString("HER2_SCORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HER2 Status.
        /// </summary>
        public static string HER2_STATUS {
            get {
                return ResourceManager.GetString("HER2_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invasive or CIS.
        /// </summary>
        public static string INVASIVE_CIS {
            get {
                return ResourceManager.GetString("INVASIVE_CIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invasive Only Grade.
        /// </summary>
        public static string INVASIVE_GRADE {
            get {
                return ResourceManager.GetString("INVASIVE_GRADE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invasive Tumour Size.
        /// </summary>
        public static string INVASIVE_TUMOUR_SIZE {
            get {
                return ResourceManager.GetString("INVASIVE_TUMOUR_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ki67%.
        /// </summary>
        public static string KI_67 {
            get {
                return ResourceManager.GetString("KI_67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LN-2.
        /// </summary>
        public static string LN2 {
            get {
                return ResourceManager.GetString("LN2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lymph Nodes.
        /// </summary>
        public static string LYMPH_NODES {
            get {
                return ResourceManager.GetString("LYMPH_NODES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lymph Nodes Positive.
        /// </summary>
        public static string LYMPH_NODES_POSITIVE {
            get {
                return ResourceManager.GetString("LYMPH_NODES_POSITIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lymph Nodes Removed.
        /// </summary>
        public static string LYMPH_NODES_REMOVED {
            get {
                return ResourceManager.GetString("LYMPH_NODES_REMOVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mammogram Date.
        /// </summary>
        public static string MAMMOGRAM_DATE {
            get {
                return ResourceManager.GetString("MAMMOGRAM_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pathology.
        /// </summary>
        public static string PATHOLOGY {
            get {
                return ResourceManager.GetString("PATHOLOGY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PR Score.
        /// </summary>
        public static string PR_SCORE {
            get {
                return ResourceManager.GetString("PR_SCORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PR Status.
        /// </summary>
        public static string PR_STATUS {
            get {
                return ResourceManager.GetString("PR_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Primary Breast Cancer Histology.
        /// </summary>
        public static string SECOND_PRIMARY {
            get {
                return ResourceManager.GetString("SECOND_PRIMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TNM Stage.
        /// </summary>
        public static string TNM_STAGE {
            get {
                return ResourceManager.GetString("TNM_STAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vascular Invasion.
        /// </summary>
        public static string VASCULAR_INVASION {
            get {
                return ResourceManager.GetString("VASCULAR_INVASION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whole Tumour Size.
        /// </summary>
        public static string WHOLE_TUMOUR_SIZE {
            get {
                return ResourceManager.GetString("WHOLE_TUMOUR_SIZE", resourceCulture);
            }
        }
    }
}
