//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROCAS2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ParticipantResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ParticipantResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PROCAS2.Resources.ParticipantResources", typeof(ParticipantResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string ADDRESS {
            get {
                return ResourceManager.GetString("ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask For Risk Letter?.
        /// </summary>
        public static string ASKFORRISK {
            get {
                return ResourceManager.GetString("ASKFORRISK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attended Screening Within 6 Weeks?.
        /// </summary>
        public static string ATTENDED_SCREENING {
            get {
                return ResourceManager.GetString("ATTENDED_SCREENING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMI.
        /// </summary>
        public static string BMI {
            get {
                return ResourceManager.GetString("BMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Position.
        /// </summary>
        public static string BREAST_SIDE {
            get {
                return ResourceManager.GetString("BREAST_SIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemo. Started?.
        /// </summary>
        public static string CHEMO {
            get {
                return ResourceManager.GetString("CHEMO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemoprevention Agreed In Clinic?.
        /// </summary>
        public static string CHEMO_AGREED {
            get {
                return ResourceManager.GetString("CHEMO_AGREED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemoprevention Details.
        /// </summary>
        public static string CHEMO_DETAILS {
            get {
                return ResourceManager.GetString("CHEMO_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemoprevention Details.
        /// </summary>
        public static string CHEMOPREVENTION {
            get {
                return ResourceManager.GetString("CHEMOPREVENTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collator Status.
        /// </summary>
        public static string COLLATOR_STATUS {
            get {
                return ResourceManager.GetString("COLLATOR_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consented.
        /// </summary>
        public static string CONSENTED {
            get {
                return ResourceManager.GetString("CONSENTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Data Received.
        /// </summary>
        public static string DATA_RECEIVED {
            get {
                return ResourceManager.GetString("DATA_RECEIVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Consented.
        /// </summary>
        public static string DATE_CONSENTED {
            get {
                return ResourceManager.GetString("DATE_CONSENTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deceased.
        /// </summary>
        public static string DECEASED {
            get {
                return ResourceManager.GetString("DECEASED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string DELETED {
            get {
                return ResourceManager.GetString("DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant Details.
        /// </summary>
        public static string DETAILS {
            get {
                return ResourceManager.GetString("DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnosed.
        /// </summary>
        public static string DIAGNOSED {
            get {
                return ResourceManager.GetString("DIAGNOSED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Appoint..
        /// </summary>
        public static string DOAA {
            get {
                return ResourceManager.GetString("DOAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string DOB {
            get {
                return ResourceManager.GetString("DOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Appoint..
        /// </summary>
        public static string DOFA {
            get {
                return ResourceManager.GetString("DOFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string EVENT_DATE {
            get {
                return ResourceManager.GetString("EVENT_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string EVENT_NAME {
            get {
                return ResourceManager.GetString("EVENT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string EVENT_USER {
            get {
                return ResourceManager.GetString("EVENT_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family History.
        /// </summary>
        public static string FAMILY_HISTORY {
            get {
                return ResourceManager.GetString("FAMILY_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FHC Referral?.
        /// </summary>
        public static string FHC_REFERRAL {
            get {
                return ResourceManager.GetString("FHC_REFERRAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Recall for Assessment Outcome.
        /// </summary>
        public static string FINAL_ASSESSMENT {
            get {
                return ResourceManager.GetString("FINAL_ASSESSMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Technical Recall Outcome.
        /// </summary>
        public static string FINAL_TECHNICAL {
            get {
                return ResourceManager.GetString("FINAL_TECHNICAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FIRST_NAME {
            get {
                return ResourceManager.GetString("FIRST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GP Address Line 1.
        /// </summary>
        public static string GP_ADD_1 {
            get {
                return ResourceManager.GetString("GP_ADD_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GP Address Line 2.
        /// </summary>
        public static string GP_ADD_2 {
            get {
                return ResourceManager.GetString("GP_ADD_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GP Address Line 3.
        /// </summary>
        public static string GP_ADD_3 {
            get {
                return ResourceManager.GetString("GP_ADD_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GP Address Line 4.
        /// </summary>
        public static string GP_ADD_4 {
            get {
                return ResourceManager.GetString("GP_ADD_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GP Details.
        /// </summary>
        public static string GP_DETAILS {
            get {
                return ResourceManager.GetString("GP_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GP Email.
        /// </summary>
        public static string GP_EMAIL {
            get {
                return ResourceManager.GetString("GP_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GP Details.
        /// </summary>
        public static string GP_MODAL_TITLE {
            get {
                return ResourceManager.GetString("GP_MODAL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GP Name.
        /// </summary>
        public static string GP_NAME {
            get {
                return ResourceManager.GetString("GP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GP Postcode.
        /// </summary>
        public static string GP_POSTCODE {
            get {
                return ResourceManager.GetString("GP_POSTCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Address Line 1.
        /// </summary>
        public static string HOME_ADD_1 {
            get {
                return ResourceManager.GetString("HOME_ADD_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Address Line 2.
        /// </summary>
        public static string HOME_ADD_2 {
            get {
                return ResourceManager.GetString("HOME_ADD_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Address Line 3.
        /// </summary>
        public static string HOME_ADD_3 {
            get {
                return ResourceManager.GetString("HOME_ADD_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Address Line 4.
        /// </summary>
        public static string HOME_ADD_4 {
            get {
                return ResourceManager.GetString("HOME_ADD_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Postcode.
        /// </summary>
        public static string HOME_POSTCODE {
            get {
                return ResourceManager.GetString("HOME_POSTCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string HOMEEMAIL {
            get {
                return ResourceManager.GetString("HOMEEMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Screening Outcome.
        /// </summary>
        public static string INITIAL_SCREENING {
            get {
                return ResourceManager.GetString("INITIAL_SCREENING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LAST_NAME {
            get {
                return ResourceManager.GetString("LAST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Date.
        /// </summary>
        public static string LETTER_RECEIVED {
            get {
                return ResourceManager.GetString("LETTER_RECEIVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk Category.
        /// </summary>
        public static string LETTER_RISK_CAT {
            get {
                return ResourceManager.GetString("LETTER_RISK_CAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk Score.
        /// </summary>
        public static string LETTER_RISK_SCORE {
            get {
                return ResourceManager.GetString("LETTER_RISK_SCORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated Date.
        /// </summary>
        public static string LETTER_SENTDATE {
            get {
                return ResourceManager.GetString("LETTER_SENTDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing List?.
        /// </summary>
        public static string MAILING_LIST {
            get {
                return ResourceManager.GetString("MAILING_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Frequent Screening?.
        /// </summary>
        public static string MORE_FREQUENT {
            get {
                return ResourceManager.GetString("MORE_FREQUENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHS Number.
        /// </summary>
        public static string NHS_NUMBER {
            get {
                return ResourceManager.GetString("NHS_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no Volpara records to display..
        /// </summary>
        public static string NO_VOLPARA_RECORDS {
            get {
                return ResourceManager.GetString("NO_VOLPARA_RECORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PARTICIPANT_NAME {
            get {
                return ResourceManager.GetString("PARTICIPANT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant {0} not found..
        /// </summary>
        public static string PARTICIPANT_NOT_FOUND {
            get {
                return ResourceManager.GetString("PARTICIPANT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Code.
        /// </summary>
        public static string POST_CODE {
            get {
                return ResourceManager.GetString("POST_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Study Information.
        /// </summary>
        public static string POST_STUDY {
            get {
                return ResourceManager.GetString("POST_STUDY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Code.
        /// </summary>
        public static string POSTCODE {
            get {
                return ResourceManager.GetString("POSTCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string QUESTION_ANSWER {
            get {
                return ResourceManager.GetString("QUESTION_ANSWER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string QUESTION_CODE {
            get {
                return ResourceManager.GetString("QUESTION_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string QUESTION_QUESTION {
            get {
                return ResourceManager.GetString("QUESTION_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string QUESTIONNAIRE_END {
            get {
                return ResourceManager.GetString("QUESTIONNAIRE_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaire Response.
        /// </summary>
        public static string QUESTIONNAIRE_RESPONSE {
            get {
                return ResourceManager.GetString("QUESTIONNAIRE_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        public static string QUESTIONNAIRE_START {
            get {
                return ResourceManager.GetString("QUESTIONNAIRE_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age (or age at death).
        /// </summary>
        public static string RELATIONSHIP_AGE {
            get {
                return ResourceManager.GetString("RELATIONSHIP_AGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age of Diagnosis.
        /// </summary>
        public static string RELATIONSHIP_AGEOFDIAGNOSIS {
            get {
                return ResourceManager.GetString("RELATIONSHIP_AGEOFDIAGNOSIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string RELATIONSHIP_CODE {
            get {
                return ResourceManager.GetString("RELATIONSHIP_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string RELATIONSHIP_DESCRIPTION {
            get {
                return ResourceManager.GetString("RELATIONSHIP_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disease.
        /// </summary>
        public static string RELATIONSHIP_DISEASE {
            get {
                return ResourceManager.GetString("RELATIONSHIP_DISEASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string RELATIONSHIP_GENDER {
            get {
                return ResourceManager.GetString("RELATIONSHIP_GENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screening No..
        /// </summary>
        public static string SCREENING_NUMBER {
            get {
                return ResourceManager.GetString("SCREENING_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screening Outcomes.
        /// </summary>
        public static string SCREENING_OUTCOMES {
            get {
                return ResourceManager.GetString("SCREENING_OUTCOMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        public static string SCREENING_SITE {
            get {
                return ResourceManager.GetString("SCREENING_SITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk Letter Generated?.
        /// </summary>
        public static string SENT_RISK {
            get {
                return ResourceManager.GetString("SENT_RISK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Image.
        /// </summary>
        public static string STUDY_DATE {
            get {
                return ResourceManager.GetString("STUDY_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study Status.
        /// </summary>
        public static string STUDY_STATUS {
            get {
                return ResourceManager.GetString("STUDY_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TITLE {
            get {
                return ResourceManager.GetString("TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string UNKNOWN {
            get {
                return ResourceManager.GetString("UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volpara Version.
        /// </summary>
        public static string VOLPARA_VERSION {
            get {
                return ResourceManager.GetString("VOLPARA_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdrawn.
        /// </summary>
        public static string WITHDRAWN {
            get {
                return ResourceManager.GetString("WITHDRAWN", resourceCulture);
            }
        }
    }
}
