//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROCAS2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PROCASRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PROCASRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PROCAS2.Resources.PROCASRes", typeof(PROCASRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 001.
        /// </summary>
        public static string EVENT_CREATED {
            get {
                return ResourceManager.GetString("EVENT_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participant created..
        /// </summary>
        public static string EVENT_CREATED_STR {
            get {
                return ResourceManager.GetString("EVENT_CREATED_STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATED:.
        /// </summary>
        public static string UPLOAD_CREATED {
            get {
                return ResourceManager.GetString("UPLOAD_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAIL:.
        /// </summary>
        public static string UPLOAD_FAIL {
            get {
                return ResourceManager.GetString("UPLOAD_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The row does not contain the required number of columns ({0})..
        /// </summary>
        public static string UPLOAD_INCORRECT_COLUMNS {
            get {
                return ResourceManager.GetString("UPLOAD_INCORRECT_COLUMNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHS Number {0} is already in the database..
        /// </summary>
        public static string UPLOAD_NHS_NUMBER_IN_DB {
            get {
                return ResourceManager.GetString("UPLOAD_NHS_NUMBER_IN_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHS Number {0} has not yet given their consent..
        /// </summary>
        public static string UPLOAD_NHS_NUMBER_NOT_CONSENTED {
            get {
                return ResourceManager.GetString("UPLOAD_NHS_NUMBER_NOT_CONSENTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHS Number {0} is not in the database..
        /// </summary>
        public static string UPLOAD_NHS_NUMBER_NOT_IN_DB {
            get {
                return ResourceManager.GetString("UPLOAD_NHS_NUMBER_NOT_IN_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHS Number {0} has been updated successfully..
        /// </summary>
        public static string UPLOAD_NHS_NUMBER_SUCCESS {
            get {
                return ResourceManager.GetString("UPLOAD_NHS_NUMBER_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHS Number {0} is too long..
        /// </summary>
        public static string UPLOAD_NHS_NUMBER_TOO_LONG {
            get {
                return ResourceManager.GetString("UPLOAD_NHS_NUMBER_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name already exists..
        /// </summary>
        public static string USER_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("USER_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is either marked as not active or has not been configured yet. Please contact the PROCAS2 team to check your record..
        /// </summary>
        public static string USER_CONFIG_INCORRECT {
            get {
                return ResourceManager.GetString("USER_CONFIG_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number consented:.
        /// </summary>
        public static string VM_DASHBOARD_NUM_CONSENT {
            get {
                return ResourceManager.GetString("VM_DASHBOARD_NUM_CONSENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number consented but without full details yet:.
        /// </summary>
        public static string VM_DASHBOARD_NUM_CONSENT_NO_DETAILS {
            get {
                return ResourceManager.GetString("VM_DASHBOARD_NUM_CONSENT_NO_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of participants:.
        /// </summary>
        public static string VM_DASHBOARD_NUM_PARC {
            get {
                return ResourceManager.GetString("VM_DASHBOARD_NUM_PARC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number yet to consent:.
        /// </summary>
        public static string VM_DASHBOARD_NUM_YET_CONSENT {
            get {
                return ResourceManager.GetString("VM_DASHBOARD_NUM_YET_CONSENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a file name.
        /// </summary>
        public static string VM_UPLOAD_NEW_FILE_NAME {
            get {
                return ResourceManager.GetString("VM_UPLOAD_NEW_FILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a file name.
        /// </summary>
        public static string VM_UPLOAD_UPDATE_FILE_NAME {
            get {
                return ResourceManager.GetString("VM_UPLOAD_UPDATE_FILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string VM_USER_ADMIN_CREATE_ACTIVE {
            get {
                return ResourceManager.GetString("VM_USER_ADMIN_CREATE_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super User.
        /// </summary>
        public static string VM_USER_ADMIN_CREATE_SUPERUSER {
            get {
                return ResourceManager.GetString("VM_USER_ADMIN_CREATE_SUPERUSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string VM_USER_ADMIN_CREATE_USERNAME {
            get {
                return ResourceManager.GetString("VM_USER_ADMIN_CREATE_USERNAME", resourceCulture);
            }
        }
    }
}
