//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROCAS2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReportResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PROCAS2.Resources.ReportResources", typeof(ReportResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask For Outstanding Risk Letters.
        /// </summary>
        public static string ASK_FOR_RISK_LETTER {
            get {
                return ResourceManager.GetString("ASK_FOR_RISK_LETTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produces a list of hashed NHS numbers of all the participants that have been flagged as ready for risk letters and have not received one yet. This can then be uploaded to CRA..
        /// </summary>
        public static string ASK_FOR_RISK_LETTER_SUMMARY {
            get {
                return ResourceManager.GetString("ASK_FOR_RISK_LETTER_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients for who a risk letter has been asked for but not received..
        /// </summary>
        public static string ASKED_FOR_LETTER_NOT_REC {
            get {
                return ResourceManager.GetString("ASKED_FOR_LETTER_NOT_REC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This report will show the NHS Number, DOB, date of first appointment and date consented of those for who we have asked for a risk letter but have not yet received one..
        /// </summary>
        public static string ASKED_FOR_LETTER_NOT_REC_SUMMARY {
            get {
                return ResourceManager.GetString("ASKED_FOR_LETTER_NOT_REC_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients consented but without full details yet.
        /// </summary>
        public static string CONSENTED_YET_TO_GET_FULL {
            get {
                return ResourceManager.GetString("CONSENTED_YET_TO_GET_FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This report will show the NHS Number, DOB, date of first appointment and date consented of those who have consented to the study, but not had the full patient details uploaded into Collator yet..
        /// </summary>
        public static string CONSENTED_YET_TO_GET_FULL_SUMMARY {
            get {
                return ResourceManager.GetString("CONSENTED_YET_TO_GET_FULL_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Detail Reports.
        /// </summary>
        public static string DETAILED_REPORTS {
            get {
                return ResourceManager.GetString("DETAILED_REPORTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating Report.
        /// </summary>
        public static string GENERATING_REPORT {
            get {
                return ResourceManager.GetString("GENERATING_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients for who we have a risk letter but it has not been sent..
        /// </summary>
        public static string GOT_LETTER_NOT_SENT {
            get {
                return ResourceManager.GetString("GOT_LETTER_NOT_SENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This report will show the NHS Number, DOB, date of first appointment and date consented for those who we have received a risk letter from CRA but not sent it yet..
        /// </summary>
        public static string GOT_LETTER_NOT_SENT_SUMMARY {
            get {
                return ResourceManager.GetString("GOT_LETTER_NOT_SENT_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients for who Volpara data has been received but no risk letter has been asked for yet.
        /// </summary>
        public static string GOT_VOLPARA_NOT_ASKED {
            get {
                return ResourceManager.GetString("GOT_VOLPARA_NOT_ASKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This report will show the NHS Number, DOB, date of first appointment and date consented of those who have received Volpara data but no risk letter has been asked for yet..
        /// </summary>
        public static string GOT_VOLPARA_NOT_ASKED_SUMMARY {
            get {
                return ResourceManager.GetString("GOT_VOLPARA_NOT_ASKED_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histology.
        /// </summary>
        public static string HISTOLOGY {
            get {
                return ResourceManager.GetString("HISTOLOGY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This report will show all histology records in the database..
        /// </summary>
        public static string HISTOLOGY_SUMMARY {
            get {
                return ResourceManager.GetString("HISTOLOGY_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string INDEX_TITLE {
            get {
                return ResourceManager.GetString("INDEX_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients invited but yet to consent.
        /// </summary>
        public static string INVITED_YET_TO_CONSENT {
            get {
                return ResourceManager.GetString("INVITED_YET_TO_CONSENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This report will show the NHS Number, DOB and date of first appointment of every person invited but who has not yet consented. .
        /// </summary>
        public static string INVITED_YET_TO_CONSENT_SUMMARY {
            get {
                return ResourceManager.GetString("INVITED_YET_TO_CONSENT_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHS Number.
        /// </summary>
        public static string NHS_NUMBER {
            get {
                return ResourceManager.GetString("NHS_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This NHS Number does not exist in the database..
        /// </summary>
        public static string NHS_NUMBER_NOT_EXIST {
            get {
                return ResourceManager.GetString("NHS_NUMBER_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Details.
        /// </summary>
        public static string PATIENT_DETAILS {
            get {
                return ResourceManager.GetString("PATIENT_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collator Status Reports.
        /// </summary>
        public static string STATUS_REPORTS {
            get {
                return ResourceManager.GetString("STATUS_REPORTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients who have consented but we&apos;ve not received Volpara data yet..
        /// </summary>
        public static string WAITING_FOR_VOLPARA {
            get {
                return ResourceManager.GetString("WAITING_FOR_VOLPARA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This report will show the NHS Number, DOB, date of first appointment and date consented for those who have consented to participate but we have yet to receive Volpara data..
        /// </summary>
        public static string WAITING_FOR_VOLPARA_SUMMARY {
            get {
                return ResourceManager.GetString("WAITING_FOR_VOLPARA_SUMMARY", resourceCulture);
            }
        }
    }
}
