//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROCAS2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ReportResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PROCAS2.Resources.ReportResources", typeof(ReportResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask For Outstanding Risk Letters.
        /// </summary>
        public static string ASK_FOR_RISK_LETTER {
            get {
                return ResourceManager.GetString("ASK_FOR_RISK_LETTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produces a text file containing a list of study number, DOB, date of first appointment and hashed NHS numbers. These are for all the participants that have been flagged as ready for risk letters and have not received one yet. This can then be uploaded to CRA..
        /// </summary>
        public static string ASK_FOR_RISK_LETTER_SUMMARY {
            get {
                return ResourceManager.GetString("ASK_FOR_RISK_LETTER_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients for who a risk letter has been asked for but not received..
        /// </summary>
        public static string ASKED_FOR_LETTER_NOT_REC {
            get {
                return ResourceManager.GetString("ASKED_FOR_LETTER_NOT_REC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This report will show the NHS Number, DOB, date of first appointment and date consented of those for who we have asked for a risk letter but have not yet received one..
        /// </summary>
        public static string ASKED_FOR_LETTER_NOT_REC_SUMMARY {
            get {
                return ResourceManager.GetString("ASKED_FOR_LETTER_NOT_REC_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breast Cancer Diagnoses.
        /// </summary>
        public static string BC_DIAGNOSES {
            get {
                return ResourceManager.GetString("BC_DIAGNOSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This report shows the NHS Number, DOB, age, ethnicity, post code, Volpara score, survey answers and risk score of every patient who has been diagnosed with breast cancer.
        /// </summary>
        public static string BC_DIAGNOSES_SUMMARY {
            get {
                return ResourceManager.GetString("BC_DIAGNOSES_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemoprevention agreed in clinic, appropriate and prescription filled in.
        /// </summary>
        public static string CHEMO_AGREE_FILLED {
            get {
                return ResourceManager.GetString("CHEMO_AGREE_FILLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemoprevention agreed in clinic but not appropriate.
        /// </summary>
        public static string CHEMO_AGREE_NOT_APP {
            get {
                return ResourceManager.GetString("CHEMO_AGREE_NOT_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemoprevention agreed in clinic, appropriate, but prescription not filled in.
        /// </summary>
        public static string CHEMO_AGREE_NOT_FILLED {
            get {
                return ResourceManager.GetString("CHEMO_AGREE_NOT_FILLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemoprevention not agreed in clinic.
        /// </summary>
        public static string CHEMO_DISAGREED {
            get {
                return ResourceManager.GetString("CHEMO_DISAGREED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemoprevention.
        /// </summary>
        public static string CHEMOPREVENTION {
            get {
                return ResourceManager.GetString("CHEMOPREVENTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This report shows the NHS Number, DOB, age, ethnicity, post code and risk score of every patient who had a chemoprevention appointment in clinic, with the outcomes selected below..
        /// </summary>
        public static string CHEMOPREVENTION_SUMMARY {
            get {
                return ResourceManager.GetString("CHEMOPREVENTION_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients who have consented.
        /// </summary>
        public static string CONSENTED {
            get {
                return ResourceManager.GetString("CONSENTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This report will show the NHS Number, DOB and date of first appointment of every person who has consented..
        /// </summary>
        public static string CONSENTED_SUMMARY {
            get {
                return ResourceManager.GetString("CONSENTED_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients consented but without full details yet.
        /// </summary>
        public static string CONSENTED_YET_TO_GET_FULL {
            get {
                return ResourceManager.GetString("CONSENTED_YET_TO_GET_FULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This report will show the NHS Number, DOB, date of first appointment and date consented of those who have consented to the study, but not had the full patient details uploaded into Collator yet..
        /// </summary>
        public static string CONSENTED_YET_TO_GET_FULL_SUMMARY {
            get {
                return ResourceManager.GetString("CONSENTED_YET_TO_GET_FULL_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Detail Reports.
        /// </summary>
        public static string DETAILED_REPORTS {
            get {
                return ResourceManager.GetString("DETAILED_REPORTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating Report.
        /// </summary>
        public static string GENERATING_REPORT {
            get {
                return ResourceManager.GetString("GENERATING_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients for who we have a risk letter but it has not been sent..
        /// </summary>
        public static string GOT_LETTER_NOT_SENT {
            get {
                return ResourceManager.GetString("GOT_LETTER_NOT_SENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This report will show the NHS Number, DOB, date of first appointment and date consented for those who we have received a risk letter from CRA but not sent it yet..
        /// </summary>
        public static string GOT_LETTER_NOT_SENT_SUMMARY {
            get {
                return ResourceManager.GetString("GOT_LETTER_NOT_SENT_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients for who Volpara data has been received but no risk letter has been asked for yet.
        /// </summary>
        public static string GOT_VOLPARA_NOT_ASKED {
            get {
                return ResourceManager.GetString("GOT_VOLPARA_NOT_ASKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This report will show the NHS Number, DOB, date of first appointment and date consented of those who have received Volpara data but no risk letter has been asked for yet..
        /// </summary>
        public static string GOT_VOLPARA_NOT_ASKED_SUMMARY {
            get {
                return ResourceManager.GetString("GOT_VOLPARA_NOT_ASKED_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Histology.
        /// </summary>
        public static string HISTOLOGY {
            get {
                return ResourceManager.GetString("HISTOLOGY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This report will show all histology records in the database..
        /// </summary>
        public static string HISTOLOGY_SUMMARY {
            get {
                return ResourceManager.GetString("HISTOLOGY_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string INDEX_TITLE {
            get {
                return ResourceManager.GetString("INDEX_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients who have been invited.
        /// </summary>
        public static string INVITED {
            get {
                return ResourceManager.GetString("INVITED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This report will show the NHS Number, DOB and date of first appointment of every person who has been invited..
        /// </summary>
        public static string INVITED_SUMMARY {
            get {
                return ResourceManager.GetString("INVITED_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients invited but yet to consent.
        /// </summary>
        public static string INVITED_YET_TO_CONSENT {
            get {
                return ResourceManager.GetString("INVITED_YET_TO_CONSENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This report will show the NHS Number, DOB and date of first appointment of every person invited but who has not yet consented. .
        /// </summary>
        public static string INVITED_YET_TO_CONSENT_SUMMARY {
            get {
                return ResourceManager.GetString("INVITED_YET_TO_CONSENT_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHS Number.
        /// </summary>
        public static string NHS_NUMBER {
            get {
                return ResourceManager.GetString("NHS_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This NHS Number does not exist in the database..
        /// </summary>
        public static string NHS_NUMBER_NOT_EXIST {
            get {
                return ResourceManager.GetString("NHS_NUMBER_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of assessment recalls.
        /// </summary>
        public static string NUMBER_ASSESS_RECALLS {
            get {
                return ResourceManager.GetString("NUMBER_ASSESS_RECALLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of recalls.
        /// </summary>
        public static string NUMBER_RECALLS {
            get {
                return ResourceManager.GetString("NUMBER_RECALLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This report shows the NHS Number, DOB, age, ethnicity, post code and risk score of every patient who had a recall of the type selected below..
        /// </summary>
        public static string NUMBER_RECALLS_SUMMARY {
            get {
                return ResourceManager.GetString("NUMBER_RECALLS_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of routine recalls.
        /// </summary>
        public static string NUMBER_ROUTINE_RECALLS {
            get {
                return ResourceManager.GetString("NUMBER_ROUTINE_RECALLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of technical recalls.
        /// </summary>
        public static string NUMBER_TECHNICAL_RECALLS {
            get {
                return ResourceManager.GetString("NUMBER_TECHNICAL_RECALLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Details.
        /// </summary>
        public static string PATIENT_DETAILS {
            get {
                return ResourceManager.GetString("PATIENT_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Reports.
        /// </summary>
        public static string PATIENT_REPORTS {
            get {
                return ResourceManager.GetString("PATIENT_REPORTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymise?.
        /// </summary>
        public static string QDB_ANONYMISE {
            get {
                return ResourceManager.GetString("QDB_ANONYMISE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Consented From.
        /// </summary>
        public static string QDB_CONSENTED_FROM {
            get {
                return ResourceManager.GetString("QDB_CONSENTED_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Consented To.
        /// </summary>
        public static string QDB_CONSENTED_TO {
            get {
                return ResourceManager.GetString("QDB_CONSENTED_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Addresses?.
        /// </summary>
        public static string QDB_INCLUDE_ADDRESSES {
            get {
                return ResourceManager.GetString("QDB_INCLUDE_ADDRESSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Histology?.
        /// </summary>
        public static string QDB_INCLUDE_HISTOLOGY {
            get {
                return ResourceManager.GetString("QDB_INCLUDE_HISTOLOGY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Most Recent Questionnaire Responses?.
        /// </summary>
        public static string QDB_MR_QUESTIONNAIRE {
            get {
                return ResourceManager.GetString("QDB_MR_QUESTIONNAIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Most Recent Risk?.
        /// </summary>
        public static string QDB_MR_RISK {
            get {
                return ResourceManager.GetString("QDB_MR_RISK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Most Recent Volpara Results?.
        /// </summary>
        public static string QDB_MR_VOLPARA {
            get {
                return ResourceManager.GetString("QDB_MR_VOLPARA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screening Site.
        /// </summary>
        public static string QDB_SCREENING_SITE {
            get {
                return ResourceManager.GetString("QDB_SCREENING_SITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On this screen you can retrieve large datasets from the Collator database, for your own analysis. The larger the dataset the longer this will take to generate, and the more computer resources it will use. This means that some things have been left out, e.g. participant audit trail and risk letter contents, and some things are optional and by default ignored. You can only extract data for one screening site at a time. The data will be exported as an Excel spreadsheet, with many worksheets. .
        /// </summary>
        public static string QDB_SUMMARY {
            get {
                return ResourceManager.GetString("QDB_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query the Collator Database.
        /// </summary>
        public static string QUERY_DATABASE {
            get {
                return ResourceManager.GetString("QUERY_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screening attendance.
        /// </summary>
        public static string SCREENING_ATTENDANCE {
            get {
                return ResourceManager.GetString("SCREENING_ATTENDANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This report shows the NHS Number, DOB, age, ethnicity, post code and risk score of every patient who attended screening within the chosen date below..
        /// </summary>
        public static string SCREENING_ATTENDANCE_SUMMARY {
            get {
                return ResourceManager.GetString("SCREENING_ATTENDANCE_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screening attendance at first offered screening episode.
        /// </summary>
        public static string SCREENING_FIRST_OFFERED {
            get {
                return ResourceManager.GetString("SCREENING_FIRST_OFFERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This report shows the NHS Number, DOB, age, ethnicity, post code and risk score of every patient who attended screening on the first offered appointment..
        /// </summary>
        public static string SCREENING_FIRST_OFFERED_SUMMARY {
            get {
                return ResourceManager.GetString("SCREENING_FIRST_OFFERED_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screening attendance within 180 days of episode opening.
        /// </summary>
        public static string SCREENING_WITHIN_180_DAYS {
            get {
                return ResourceManager.GetString("SCREENING_WITHIN_180_DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This report shows the NHS Number, DOB, age, ethnicity, post code and risk score of every patient who attended screening within 180 days of the first offered appointment..
        /// </summary>
        public static string SCREENING_WITHIN_180_DAYS_SUMMARY {
            get {
                return ResourceManager.GetString("SCREENING_WITHIN_180_DAYS_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collator Status Reports.
        /// </summary>
        public static string STATUS_REPORTS {
            get {
                return ResourceManager.GetString("STATUS_REPORTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subsequent consultations.
        /// </summary>
        public static string SUBSEQUENT_CONSULTATION {
            get {
                return ResourceManager.GetString("SUBSEQUENT_CONSULTATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This report shows the NHS Number, DOB, age, ethnicity, post code and risk score of every patient who attended subsequent consultations of the type below..
        /// </summary>
        public static string SUBSEQUENT_CONSULTATION_SUMMARY {
            get {
                return ResourceManager.GetString("SUBSEQUENT_CONSULTATION_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family History Services.
        /// </summary>
        public static string SUBSEQUENT_FAMILY_HISTORY {
            get {
                return ResourceManager.GetString("SUBSEQUENT_FAMILY_HISTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Frequent Screening.
        /// </summary>
        public static string SUBSEQUENT_MORE_FREQUENT {
            get {
                return ResourceManager.GetString("SUBSEQUENT_MORE_FREQUENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volpara.
        /// </summary>
        public static string VOLPARA {
            get {
                return ResourceManager.GetString("VOLPARA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This report will show all the Volpara record in the database..
        /// </summary>
        public static string VOLPARA_SUMMARY {
            get {
                return ResourceManager.GetString("VOLPARA_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients who have consented but we&apos;ve not received Volpara data yet..
        /// </summary>
        public static string WAITING_FOR_VOLPARA {
            get {
                return ResourceManager.GetString("WAITING_FOR_VOLPARA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients who have consented but we&apos;ve not received Volpara data yet, and it is within 2 weeks of their 6 week deadline..
        /// </summary>
        public static string WAITING_FOR_VOLPARA_NEAR_6_WEEKS {
            get {
                return ResourceManager.GetString("WAITING_FOR_VOLPARA_NEAR_6_WEEKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This report will show the NHS Number, DOB, date of first appointment and date consented for those who have consented to participate but we have yet to receive Volpara data and it is within 2 weeks of their deadline..
        /// </summary>
        public static string WAITING_FOR_VOLPARA_NEAR_6_WEEKS_SUMMARY {
            get {
                return ResourceManager.GetString("WAITING_FOR_VOLPARA_NEAR_6_WEEKS_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This report will show the NHS Number, DOB, date of first appointment and date consented for those who have consented to participate but we have yet to receive Volpara data..
        /// </summary>
        public static string WAITING_FOR_VOLPARA_SUMMARY {
            get {
                return ResourceManager.GetString("WAITING_FOR_VOLPARA_SUMMARY", resourceCulture);
            }
        }
    }
}
