//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROCAS2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SiteResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SiteResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PROCAS2.Resources.SiteResources", typeof(SiteResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Participants.
        /// </summary>
        public static string NUM_OF_PARTICIPANTS {
            get {
                return ResourceManager.GetString("NUM_OF_PARTICIPANTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string SITE_ADDRESS {
            get {
                return ResourceManager.GetString("SITE_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string SITE_CODE {
            get {
                return ResourceManager.GetString("SITE_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer Left Image Resource Name.
        /// </summary>
        public static string SITE_IMAGEFOOTERLEFT {
            get {
                return ResourceManager.GetString("SITE_IMAGEFOOTERLEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer Left Image Height in cm.
        /// </summary>
        public static string SITE_IMAGEFOOTERLEFT_HEIGHT {
            get {
                return ResourceManager.GetString("SITE_IMAGEFOOTERLEFT_HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer Left Image Width in cm.
        /// </summary>
        public static string SITE_IMAGEFOOTERLEFT_WIDTH {
            get {
                return ResourceManager.GetString("SITE_IMAGEFOOTERLEFT_WIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer Right Image Resource Name.
        /// </summary>
        public static string SITE_IMAGEFOOTERRIGHT {
            get {
                return ResourceManager.GetString("SITE_IMAGEFOOTERRIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer Right Image Height in cm.
        /// </summary>
        public static string SITE_IMAGEFOOTERRIGHT_HEIGHT {
            get {
                return ResourceManager.GetString("SITE_IMAGEFOOTERRIGHT_HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer Right Image Width in cm.
        /// </summary>
        public static string SITE_IMAGEFOOTERRIGHT_WIDTH {
            get {
                return ResourceManager.GetString("SITE_IMAGEFOOTERRIGHT_WIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Right Image Resource Name.
        /// </summary>
        public static string SITE_IMAGEHEADERRIGHT {
            get {
                return ResourceManager.GetString("SITE_IMAGEHEADERRIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Right Image Height in cm.
        /// </summary>
        public static string SITE_IMAGEHEADERRIGHT_HEIGHT {
            get {
                return ResourceManager.GetString("SITE_IMAGEHEADERRIGHT_HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Right Image Width in cm.
        /// </summary>
        public static string SITE_IMAGEHEADERRIGHT_WIDTH {
            get {
                return ResourceManager.GetString("SITE_IMAGEHEADERRIGHT_WIDTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SITE_NAME {
            get {
                return ResourceManager.GetString("SITE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Person the Letters are From.
        /// </summary>
        public static string SITE_NAMEFROM {
            get {
                return ResourceManager.GetString("SITE_NAMEFROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Code.
        /// </summary>
        public static string SITE_POSTCODE {
            get {
                return ResourceManager.GetString("SITE_POSTCODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature Resource Name.
        /// </summary>
        public static string SITE_SIGNATURE {
            get {
                return ResourceManager.GetString("SITE_SIGNATURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sites.
        /// </summary>
        public static string SITE_TITLE {
            get {
                return ResourceManager.GetString("SITE_TITLE", resourceCulture);
            }
        }
    }
}
