//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROCAS2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UploadResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UploadResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PROCAS2.Resources.UploadResources", typeof(UploadResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line 1 is mandatory..
        /// </summary>
        public static string UPLOAD_ADDRESS_1_EMPTY {
            get {
                return ResourceManager.GetString("UPLOAD_ADDRESS_1_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line 1 is too long..
        /// </summary>
        public static string UPLOAD_ADDRESS_1_TOO_LONG {
            get {
                return ResourceManager.GetString("UPLOAD_ADDRESS_1_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line 2 is too long..
        /// </summary>
        public static string UPLOAD_ADDRESS_2_TOO_LONG {
            get {
                return ResourceManager.GetString("UPLOAD_ADDRESS_2_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line 3 is too long..
        /// </summary>
        public static string UPLOAD_ADDRESS_3_TOO_LONG {
            get {
                return ResourceManager.GetString("UPLOAD_ADDRESS_3_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line 4 is too long..
        /// </summary>
        public static string UPLOAD_ADDRESS_4_TOO_LONG {
            get {
                return ResourceManager.GetString("UPLOAD_ADDRESS_4_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a file name.
        /// </summary>
        public static string UPLOAD_ASK_RISK_FILE_NAME {
            get {
                return ResourceManager.GetString("UPLOAD_ASK_RISK_FILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Ask Risk&apos; flag for {0} has been updated successfully. .
        /// </summary>
        public static string UPLOAD_ASK_RISK_SUCCESS {
            get {
                return ResourceManager.GetString("UPLOAD_ASK_RISK_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUCCESS:.
        /// </summary>
        public static string UPLOAD_ASKRISK {
            get {
                return ResourceManager.GetString("UPLOAD_ASKRISK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMI should be an integer (whole number).
        /// </summary>
        public static string UPLOAD_BMI_WRONG_FORMAT {
            get {
                return ResourceManager.GetString("UPLOAD_BMI_WRONG_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATED:.
        /// </summary>
        public static string UPLOAD_CREATED {
            get {
                return ResourceManager.GetString("UPLOAD_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of actual appointment does not seem to set to a sensible value..
        /// </summary>
        public static string UPLOAD_DOAA_OUT_OF_RANGE {
            get {
                return ResourceManager.GetString("UPLOAD_DOAA_OUT_OF_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth is mandatory..
        /// </summary>
        public static string UPLOAD_DOB_EMPTY {
            get {
                return ResourceManager.GetString("UPLOAD_DOB_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date of birth does not seem to be set to a sensible value..
        /// </summary>
        public static string UPLOAD_DOB_OUT_OF_RANGE {
            get {
                return ResourceManager.GetString("UPLOAD_DOB_OUT_OF_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the date of birth in dd/mm/yyyy format..
        /// </summary>
        public static string UPLOAD_DOB_WRONG_FORMAT {
            get {
                return ResourceManager.GetString("UPLOAD_DOB_WRONG_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of first appointment is mandatory..
        /// </summary>
        public static string UPLOAD_DOFA_EMPTY {
            get {
                return ResourceManager.GetString("UPLOAD_DOFA_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date of first appointment does not seem to be set to a sensible value..
        /// </summary>
        public static string UPLOAD_DOFA_OUT_OF_RANGE {
            get {
                return ResourceManager.GetString("UPLOAD_DOFA_OUT_OF_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the date of first appointment in dd/mm/yyyy format..
        /// </summary>
        public static string UPLOAD_DOFA_WRONG_FORMAT {
            get {
                return ResourceManager.GetString("UPLOAD_DOFA_WRONG_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address is too long..
        /// </summary>
        public static string UPLOAD_EMAIL_TOO_LONG {
            get {
                return ResourceManager.GetString("UPLOAD_EMAIL_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAIL:.
        /// </summary>
        public static string UPLOAD_FAIL {
            get {
                return ResourceManager.GetString("UPLOAD_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is mandatory..
        /// </summary>
        public static string UPLOAD_FIRST_NAME_EMPTY {
            get {
                return ResourceManager.GetString("UPLOAD_FIRST_NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is too long..
        /// </summary>
        public static string UPLOAD_FIRST_NAME_TOO_LONG {
            get {
                return ResourceManager.GetString("UPLOAD_FIRST_NAME_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GP Address line 1 is mandatory..
        /// </summary>
        public static string UPLOAD_GP_ADDRESS_1_EMPTY {
            get {
                return ResourceManager.GetString("UPLOAD_GP_ADDRESS_1_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GP Address line 1 is too long..
        /// </summary>
        public static string UPLOAD_GP_ADDRESS_1_TOO_LONG {
            get {
                return ResourceManager.GetString("UPLOAD_GP_ADDRESS_1_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GP Address line 2 is too long..
        /// </summary>
        public static string UPLOAD_GP_ADDRESS_2_TOO_LONG {
            get {
                return ResourceManager.GetString("UPLOAD_GP_ADDRESS_2_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GP Address line 3 is too long..
        /// </summary>
        public static string UPLOAD_GP_ADDRESS_3_TOO_LONG {
            get {
                return ResourceManager.GetString("UPLOAD_GP_ADDRESS_3_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GP Address line 4 is too long..
        /// </summary>
        public static string UPLOAD_GP_ADDRESS_4_TOO_LONG {
            get {
                return ResourceManager.GetString("UPLOAD_GP_ADDRESS_4_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GP Email address is too long..
        /// </summary>
        public static string UPLOAD_GP_EMAIL_TOO_LONG {
            get {
                return ResourceManager.GetString("UPLOAD_GP_EMAIL_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GP Name is mandatory..
        /// </summary>
        public static string UPLOAD_GP_NAME_EMPTY {
            get {
                return ResourceManager.GetString("UPLOAD_GP_NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GP Name is too long..
        /// </summary>
        public static string UPLOAD_GP_NAME_TOO_LONG {
            get {
                return ResourceManager.GetString("UPLOAD_GP_NAME_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GP Postcode is mandatory..
        /// </summary>
        public static string UPLOAD_GP_POSTCODE_EMPTY {
            get {
                return ResourceManager.GetString("UPLOAD_GP_POSTCODE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GP Postcode is too long..
        /// </summary>
        public static string UPLOAD_GP_POSTCODE_TOO_LONG {
            get {
                return ResourceManager.GetString("UPLOAD_GP_POSTCODE_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The row does not contain the required number of columns ({0})..
        /// </summary>
        public static string UPLOAD_INCORRECT_COLUMNS {
            get {
                return ResourceManager.GetString("UPLOAD_INCORRECT_COLUMNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is mandatory..
        /// </summary>
        public static string UPLOAD_LAST_NAME_EMPTY {
            get {
                return ResourceManager.GetString("UPLOAD_LAST_NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is too long..
        /// </summary>
        public static string UPLOAD_LAST_NAME_TOO_LONG {
            get {
                return ResourceManager.GetString("UPLOAD_LAST_NAME_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing list flag should be either Y or N..
        /// </summary>
        public static string UPLOAD_MAILING_LIST_WRONG_FORMAT {
            get {
                return ResourceManager.GetString("UPLOAD_MAILING_LIST_WRONG_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column 2 must be set to &apos;yes&apos;..
        /// </summary>
        public static string UPLOAD_MUST_BE_YES {
            get {
                return ResourceManager.GetString("UPLOAD_MUST_BE_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a file name.
        /// </summary>
        public static string UPLOAD_NEW_FILE_NAME {
            get {
                return ResourceManager.GetString("UPLOAD_NEW_FILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regenerate hashes for existing numbers?.
        /// </summary>
        public static string UPLOAD_NEW_REGENERATE {
            get {
                return ResourceManager.GetString("UPLOAD_NEW_REGENERATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHS Number {0} has already been updated. Please edit manually..
        /// </summary>
        public static string UPLOAD_NHS_NUMBER_ALREADY_UPDATED {
            get {
                return ResourceManager.GetString("UPLOAD_NHS_NUMBER_ALREADY_UPDATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHS Number is mandatory.
        /// </summary>
        public static string UPLOAD_NHS_NUMBER_EMPTY {
            get {
                return ResourceManager.GetString("UPLOAD_NHS_NUMBER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHS Number {0} is already in the database..
        /// </summary>
        public static string UPLOAD_NHS_NUMBER_IN_DB {
            get {
                return ResourceManager.GetString("UPLOAD_NHS_NUMBER_IN_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHS Number {0} has not yet given their consent..
        /// </summary>
        public static string UPLOAD_NHS_NUMBER_NOT_CONSENTED {
            get {
                return ResourceManager.GetString("UPLOAD_NHS_NUMBER_NOT_CONSENTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHS Number {0} is not in the database..
        /// </summary>
        public static string UPLOAD_NHS_NUMBER_NOT_IN_DB {
            get {
                return ResourceManager.GetString("UPLOAD_NHS_NUMBER_NOT_IN_DB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHS Number {0} has been updated successfully..
        /// </summary>
        public static string UPLOAD_NHS_NUMBER_SUCCESS {
            get {
                return ResourceManager.GetString("UPLOAD_NHS_NUMBER_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHS Number is too long..
        /// </summary>
        public static string UPLOAD_NHS_NUMBER_TOO_LONG {
            get {
                return ResourceManager.GetString("UPLOAD_NHS_NUMBER_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode is mandatory..
        /// </summary>
        public static string UPLOAD_POSTCODE_EMPTY {
            get {
                return ResourceManager.GetString("UPLOAD_POSTCODE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode is too long..
        /// </summary>
        public static string UPLOAD_POSTCODE_TOO_LONG {
            get {
                return ResourceManager.GetString("UPLOAD_POSTCODE_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screening Number is mandatory..
        /// </summary>
        public static string UPLOAD_SCREEN_NUMBER_EMPTY {
            get {
                return ResourceManager.GetString("UPLOAD_SCREEN_NUMBER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screening Number is too long..
        /// </summary>
        public static string UPLOAD_SCREEN_NUMBER_TOO_LONG {
            get {
                return ResourceManager.GetString("UPLOAD_SCREEN_NUMBER_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The site code is mandatory..
        /// </summary>
        public static string UPLOAD_SITE_CODE_EMPTY {
            get {
                return ResourceManager.GetString("UPLOAD_SITE_CODE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The site code is too long..
        /// </summary>
        public static string UPLOAD_SITE_CODE_TOO_LONG {
            get {
                return ResourceManager.GetString("UPLOAD_SITE_CODE_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site code {0} does not exist..
        /// </summary>
        public static string UPLOAD_SITE_CODE_WRONG {
            get {
                return ResourceManager.GetString("UPLOAD_SITE_CODE_WRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title is too long..
        /// </summary>
        public static string UPLOAD_TITLE_TOO_LONG {
            get {
                return ResourceManager.GetString("UPLOAD_TITLE_TOO_LONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a file name.
        /// </summary>
        public static string UPLOAD_UPDATE_FILE_NAME {
            get {
                return ResourceManager.GetString("UPLOAD_UPDATE_FILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUCCESS:.
        /// </summary>
        public static string UPLOAD_UPDATED {
            get {
                return ResourceManager.GetString("UPLOAD_UPDATED", resourceCulture);
            }
        }
    }
}
