//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROCAS2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VolparaResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VolparaResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PROCAS2.Resources.VolparaResources", typeof(VolparaResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create the image record.
        /// </summary>
        public static string CANNOT_CREATE_IMAGE {
            get {
                return ResourceManager.GetString("CANNOT_CREATE_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create Volpara record in the database..
        /// </summary>
        public static string CANNOT_CREATE_RECORD {
            get {
                return ResourceManager.GetString("CANNOT_CREATE_RECORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot store the Volpara message for patient {0}.
        /// </summary>
        public static string CANNOT_STORE_VOLPARA {
            get {
                return ResourceManager.GetString("CANNOT_STORE_VOLPARA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The filename has not been supplied for at least one of the images..
        /// </summary>
        public static string FILENAME_NOT_EXISTS {
            get {
                return ResourceManager.GetString("FILENAME_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The patient ID {0} does not exist.
        /// </summary>
        public static string PATIENT_NOT_EXISTS {
            get {
                return ResourceManager.GetString("PATIENT_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SourceImage section does not exist for at least one of the images..
        /// </summary>
        public static string SOURCEIMAGE_NOT_EXISTS {
            get {
                return ResourceManager.GetString("SOURCEIMAGE_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XlsData section does not exist for at least one of the images..
        /// </summary>
        public static string XLSDATA_NOT_EXISTS {
            get {
                return ResourceManager.GetString("XLSDATA_NOT_EXISTS", resourceCulture);
            }
        }
    }
}
